import type { ManualConceptContent } from "./types.ts";

export const boundariesContent: Record<string, ManualConceptContent> = {
  "Named languages": {
    plain: "‘汉语’‘英语’等名称是社会为了教学、治理和认同划出的类别，不等于每个人头脑里天然分开的盒子。",
    kind: "生活例子",
    exampleZh: "学校把课程分成中文课和英文课，护照也记录‘母语’，这些名称方便管理；但学生解题时会同时借助两边学到的词、概念和表达。名称是真实的社会分类，却未必是心理系统的天然边界。",
    exampleEn: "A school separates Chinese and English classes and a passport records a ‘mother tongue,’ yet a student draws on concepts learned through both when solving a problem. The labels are socially real categories, not necessarily natural mental boundaries.",
  },
  "Ontology of named languages": {
    plain: "它追问：英语、汉语这些被命名的语言，究竟是独立存在的实体，还是社会历史建构出来的分类？",
    kind: "思想实验",
    exampleZh: "假设一个海港社区几百年来形成连续变化的说话方式，邻村彼此听得懂，政府后来却画线规定线东叫A语、线西叫B语。这个案例用来追问：A语和B语的‘存在’，来自语言结构本身还是政治命名？",
    exampleEn: "Imagine a port region with a centuries-old continuum of mutually intelligible speech. A government later draws a border and names the eastern side Language A and the western side Language B. The case asks whether A and B exist as structural entities or through political naming.",
  },
  "I-language": {
    plain: "一个人头脑中已经形成、能让他理解和造出新句子的语言知识系统。",
    kind: "生活例子",
    exampleZh: "小美从未听过‘哪本书他昨天买了？’这个具体句子，却能理解它，也能判断某些词序很别扭。这里关注的不是词典收了多少句子，而是她头脑中能生成和判断新句子的知识。",
    exampleEn: "Mei has never heard the exact sentence ‘Which book did he buy yesterday?’ but understands it and can reject ill-formed word orders. The focus is the internal knowledge that generates and judges new sentences, not a collection in a dictionary.",
  },
  "E-language": {
    plain: "词典、语料库、录音和社会规范中可以从外部观察和收集的语言。",
    kind: "生活例子",
    exampleZh: "研究班级语言时，老师收集学生作文、聊天录音和校规中的用语，再统计哪些表达最常出现。这些可保存、比较的外部材料属于E-language层面；它们不能直接等同于某个学生头脑中的完整语法。",
    exampleEn: "A teacher collects essays, recordings, and school rules and counts recurring expressions. These observable records belong to E-language; they are not identical to any student’s complete internal grammar.",
  },
  "Linguistic repertoire": {
    plain: "一个人在不同生活经历中积累、需要时可以调用的全部语言资源。",
    kind: "生活例子",
    exampleZh: "阿杰会家乡话、普通话、一些英语专业词、游戏黑话和正式邮件写法。他并非每一项都同样熟练，但会按对象和任务选择使用；这些资源合起来就是他的语言资源库。",
    exampleEn: "Jie knows a home variety, Mandarin, English technical terms, gaming slang, and formal email conventions. His proficiency is uneven, but the resources he can mobilize across situations form his linguistic repertoire.",
  },
  "Unitary repertoire": {
    plain: "说话者使用资源时，并不是先打开一个语言盒子再关闭它，而是从一个整合资源库中选择。",
    kind: "课堂例子",
    exampleZh: "学生解释电路时说‘这个 current 走到这里就分流’，同时画箭头。他没有停下来决定先使用完整中文还是完整英语，而是直接从自己会的全部资源中挑选最合适的表达。",
    exampleEn: "Explaining a circuit, a student says, ‘This current reaches here and then branches,’ while drawing arrows. The student selects fitting resources from an integrated repertoire rather than opening one complete language system at a time.",
  },
  "Idiolect": {
    plain: "某一个人长期形成的、带有个人特点的说话和写作方式。",
    kind: "生活例子",
    exampleZh: "小周经常用‘怎么说呢’开头，给亲近朋友发消息会重复句尾，还爱把家乡话词放进普通话。别人一看这些习惯就猜到是他；这组个人化规律就是他的个体语。",
    exampleEn: "Zhou often begins with a favorite hesitation, repeats sentence endings in messages, and inserts home-variety words into Mandarin. Friends recognize the pattern as his characteristic idiolect.",
  },
  "Single grammar thesis": {
    plain: "双语者可能用一套整合语法组织全部语言特征，而不是让两套完整语法轮流接管。",
    kind: "分析示例",
    exampleZh: "儿童反复说出‘I already 吃过了’一类从未背过的新句子，英语词序、汉语体标记和整句意义持续遵守同一组组合规律。只有这种系统证据才支持单一语法分析；仅仅在不同场合使用多种语言并不能证明它。",
    exampleEn: "A child repeatedly creates novel utterances such as ‘I already chi-guo-le,’ where English ordering and Chinese aspect markers obey one systematic pattern. Such evidence can support a single-grammar analysis; merely using several languages in different settings cannot.",
  },
  "Two-grammar assumption": {
    plain: "双语者拥有两套相对独立的语法；混合表达时，两套语法仍分别提供结构限制。",
    kind: "分析示例",
    exampleZh: "一名双语者只说英语时稳定遵守英语句法，只说汉语时稳定遵守汉语句法，混合句也主要出现在两套结构都许可的边界。两套语法假设会把这种规律解释为两个系统的互动，而非一个统一语法。",
    exampleEn: "A bilingual consistently follows English syntax in English-only speech and Chinese syntax in Chinese-only speech, while mixed clauses occur at boundaries licensed by both. A two-grammar account treats this as interaction between two systems.",
  },
  "Feature-to-language assignment": {
    plain: "分析前先把某个词、声音或语法标成‘属于英语／汉语’的分类步骤。",
    kind: "分析示例",
    exampleZh: "整理对话时，编码者把-ed标成‘英语过去时特征’，把‘了’标成‘汉语体特征’，再统计两类怎样组合。这个贴标签步骤是研究者的分析选择，不能反过来证明说话者头脑里本来就有同样边界。",
    exampleEn: "A coder labels -ed an ‘English past-tense feature’ and le a ‘Chinese aspect feature’ before counting combinations. The assignment is an analytic decision and does not prove that the speaker’s mind contains the same boundary.",
  },
  "Code-switching": {
    plain: "互动中从一个可识别的语言或变体转换到另一个。",
    kind: "生活例子",
    exampleZh: "小王先用普通话向全组说明任务，看到新来的交换生没听懂，随即改用英语重说一遍。转换发生在明确可识别的两个语码之间，并服务于听众变化，因此可分析为语码转换。",
    exampleEn: "Wang explains a task in Mandarin, notices that an exchange student has not understood, and repeats it in English. The shift between recognizable codes responds to a change in audience and can be analyzed as code-switching.",
  },
  "Code-mixing": {
    plain: "在同一句或同一小段话里，把通常归入不同语言的成分组合起来。",
    kind: "生活例子",
    exampleZh: "朋友说‘这个方案太 time-consuming 了’，把英语形容成分放进汉语句法框架。这里关注的是句内成分怎样混合，而不是谈话在完整中文段和英文段之间转换。",
    exampleEn: "A friend says, ‘This plan is too time-consuming le,’ inserting an English expression into a Chinese syntactic frame. The focus is intra-utterance mixing rather than alternation between full stretches of two codes.",
  },
  "Polylanguaging": {
    plain: "人们会使用多种语言的少量特征，即使并不完整掌握那些语言。",
    kind: "生活例子",
    exampleZh: "一群球迷不会完整说西班牙语，却会在中文聊天中使用vamos、gol等词来营造共同气氛。分析重点不是他们是否‘会西班牙语’，而是怎样调用多种语言特征表达身份。",
    exampleEn: "Football fans who do not speak Spanish fluently use words such as vamos and gol in Chinese chat to create shared excitement. Polylanguaging concerns their use of features from several languages, not full command of each language.",
  },
  "Metrolingualism": {
    plain: "城市里的人把多种语言资源当作日常生活材料，随场所、工作和关系灵活组合。",
    kind: "生活例子",
    exampleZh: "夜市摊主用粤语招呼熟客、普通话报价、英语数字和手势服务游客，还借用邻摊的越南语称呼。这个城市商业实践不是几套完整语言的轮换，而是人、场所和资源的灵活组合。",
    exampleEn: "A market vendor uses Cantonese with regulars, Mandarin for prices, English numbers and gesture with tourists, and a Vietnamese greeting learned next door. The urban practice flexibly assembles people, place, and resources.",
  },
  "Transidiomatic practice": {
    plain: "跨地域的人借助聊天软件、视频和移动生活，形成不受单一地点限制的交流方式。",
    kind: "生活例子",
    exampleZh: "移民家庭的群聊连接奥克兰、广州和多伦多；成员发送粤语语音、英文链接、普通话文字和表情包，日常协商照护与汇款。交流共同体由移动通信维系，不再局限于同一地方。",
    exampleEn: "A migrant family chat links Auckland, Guangzhou, and Toronto through Cantonese voice notes, English links, Mandarin text, and memes while coordinating care and remittances. Mobile communication sustains a translocal practice.",
  },
  "Translingualism": {
    plain: "把跨越语言规范、重新协商意义看作正常交流原则，而不是偏离标准的例外。",
    kind: "分析示例",
    exampleZh: "作者在英文小说中保留未翻译的亲属称谓，让读者从上下文学习其情感含义。作品没有追求两种语言间完全对应，而是要求意义在接触中被协商；这体现跨语主义立场。",
    exampleEn: "A novelist retains an untranslated kinship term in an English text and lets readers infer its affective meaning from context. Meaning is negotiated across difference rather than made fully equivalent, reflecting translingualism.",
  },
  "Translingual practice": {
    plain: "人们在实际写作或互动中跨越既定语言规范，并与别人协商怎样理解。",
    kind: "课堂例子",
    exampleZh: "学生在英文博客中使用中文成语并附上自己的英文解释，同伴留言讨论这个解释是否保留了讽刺意味。这个具体写作与协商过程就是跨语实践，而translingualism是更一般的理论立场。",
    exampleEn: "A student uses a Chinese idiom in an English blog, supplies an original explanation, and discusses with peers whether its irony survives. This situated writing and negotiation is a translingual practice; translingualism is the broader orientation.",
  },
  "Plurilingualism": {
    plain: "一个人的多种语言能力可以强弱不一，但会组成一套可以联合使用的个人能力。",
    kind: "生活例子",
    exampleZh: "旅行者能用流利英语订房、用初级法语点餐、靠西班牙语看路牌；他不需要在每种语言中达到同样水平，仍可组合这些不均衡能力完成旅程。",
    exampleEn: "A traveler books hotels in fluent English, orders food in basic French, and reads signs in Spanish. Uneven competences combine into a plurilingual repertoire without equal proficiency in each language.",
  },
  "Multilingualism": {
    plain: "个人或社会空间中存在并使用不止一种语言。",
    kind: "生活例子",
    exampleZh: "社区诊所每天接待说普通话、萨摩亚语、英语和韩语的病人，并安排多语标识和口译服务。这里描述的是一个社会空间中多种语言的共存与使用。",
    exampleEn: "A community clinic serves patients who use Mandarin, Samoan, English, and Korean and provides multilingual signs and interpreters. This is multilingualism at the level of a social setting.",
  },
  "Bilingualism": {
    plain: "一个人或群体在生活中持续使用两种语言资源，不要求两边同样熟练。",
    kind: "生活例子",
    exampleZh: "孩子在家用粤语和祖父母聊天，在学校用英语学习，能根据对象完成日常任务。即使粤语口语强、英语读写强，他仍属于双语使用者，而不是必须两种语言都像单语者。",
    exampleEn: "A child uses Cantonese with grandparents and English at school. Stronger Cantonese speaking and stronger English literacy still constitute bilingualism; equal monolingual-like proficiency is not required.",
  },
  "Parallel monolingualism": {
    plain: "把双语者当成两个单语者，要求两种语言始终分开、分别达到单语标准。",
    kind: "课堂例子",
    exampleZh: "学校规定上午课程只能英语、下午课程只能中文，学生跨语言解释即使帮助理解也被纠正。这个安排把双语教育做成两套并排的单语教育，因此属于平行单语主义。",
    exampleEn: "A school requires English only in morning lessons and Chinese only in afternoon lessons, correcting cross-language explanations even when they aid learning. Bilingual education becomes two parallel monolingual programs.",
  },
  "Monoglossic ideology": {
    plain: "认为真正正常、纯正的交流应当只使用一种边界清楚的标准语言。",
    kind: "生活例子",
    exampleZh: "家长说‘一句话里夹英文就是中文不好’，并把纯粹、标准、单一语言当成唯一正确形式。这种评价不是中性的语言事实，而是单语纯正观。",
    exampleEn: "A parent claims that inserting English proves poor Chinese and treats pure, standard, single-language speech as the only correct form. This judgment expresses a monoglossic ideology.",
  },
  "Language separation": {
    plain: "通过时间、空间、教师或任务规则，把不同语言的使用明确分开。",
    kind: "课堂例子",
    exampleZh: "双语班用蓝色教室上英语课、绿色教室上中文课，教师要求学生进门后只用该教室指定语言。这里的核心是制度主动安排语言边界，而不是学生自然选择。",
    exampleEn: "A bilingual program uses a blue room for English and a green room for Chinese and requires the designated language after entry. The institution actively engineers language separation.",
  },
  "Coordinated translanguaging": {
    plain: "教师有计划地安排学生在不同语言和符号资源之间移动，以完成同一个学习目标。",
    kind: "课堂例子",
    exampleZh: "历史课先让学生读英文史料，再用中文小组讨论因果关系，最后制作双语时间线。每一步由教师协调，并共同服务于理解同一历史问题。",
    exampleEn: "Students read an English source, discuss causation in Chinese, and create a bilingual timeline. The teacher coordinates movement across resources toward one history-learning goal.",
  },
  "Unilateral translanguaging": {
    plain: "一方可以灵活使用多语资源，但另一方仍坚持只用一种语言或只接受一种语言。",
    kind: "生活例子",
    exampleZh: "病人用粤语、普通话和手势说明症状，医生听得懂部分粤语，却始终只用英语回应并要求病历用英语。资源流动主要发生在病人一方，因此是不对称的单边跨语。",
    exampleEn: "A patient explains symptoms through Cantonese, Mandarin, and gesture, while the doctor responds only in English and requires English records. Resource flexibility occurs mainly on one side, making translanguaging unilateral.",
  },
  "Bidialectism": {
    plain: "一个人能在生活中使用同一语言的两种方言或变体。",
    kind: "生活例子",
    exampleZh: "学生在家使用苏格兰英语方言，在课堂正式发言时使用标准英语，并能根据听众调整。这里是两种方言能力，不一定涉及两种被命名语言。",
    exampleEn: "A student uses Scots at home and Standard English in formal classroom talk, adjusting by audience. This is competence across two dialects, not necessarily two named languages.",
  },
  "Transregistering": {
    plain: "在一次活动中跨越正式、专业、亲密等语域资源来重新组织意义和关系。",
    kind: "课堂例子",
    exampleZh: "医学生先用专业术语向导师报告，再立刻用日常比喻向病人解释同一诊断，并把病人的说法带回讨论。这个跨语域移动改变了谁能理解和参与。",
    exampleEn: "A medical student reports to a supervisor in technical language, explains the diagnosis to a patient through an everyday analogy, and brings the patient’s wording back into discussion. Movement across registers redistributes understanding and participation.",
  },
  "Transregisters": {
    plain: "人们实际使用的表达会跨越传统语域边界，形成混合而可识别的资源组合。",
    kind: "生活例子",
    exampleZh: "科普主播同时使用论文术语、网络梗、动态图和朋友式称呼，形成既专业又亲近的稳定表达组合。这个组合不是单一正式或非正式语域，而是跨语域资源。",
    exampleEn: "A science creator combines research terminology, internet memes, animation, and friendly address into a recognizable professional-yet-intimate style. The configuration is a transregister rather than one bounded formal or informal register.",
  },
  "Register": {
    plain: "某类活动、参与关系和媒介通常会使用的一组表达方式。",
    kind: "生活例子",
    exampleZh: "同一个人给导师写邮件用‘烦请查收’，给朋友发消息用‘你看看’。这种差别不是地域方言，而是学术邮件与朋友聊天两类活动对应的不同语域。",
    exampleEn: "The same person writes ‘Please find attached’ to a supervisor and ‘Have a look’ to a friend. The contrast reflects registers associated with academic email and friendly chat, not regional dialects.",
  },
  "Style": {
    plain: "说话者在具体时刻选择怎样说，以表现身份、立场或与听者的关系。",
    kind: "生活例子",
    exampleZh: "歌手接受新闻采访时说得正式，直播见到老粉丝后故意恢复家乡口音来显得亲近。这个有身份目的的即时选择属于风格，而不是整个活动固定的语域。",
    exampleEn: "A singer speaks formally in a news interview but adopts a hometown accent with longtime fans during a livestream to create intimacy. The identity-oriented choice is style rather than an activity-wide register.",
  },
  "Crosslinguistic repertoire": {
    plain: "一个人可以跨越被命名语言调用、比较和组合的全部资源。",
    kind: "课堂例子",
    exampleZh: "学生写生物报告时用中文记忆口诀理解过程、用英语查关键词、用拉丁词根猜术语，再用图示整合。这些跨语言协同资源构成他的跨语言资源库。",
    exampleEn: "Writing a biology report, a student uses a Chinese mnemonic, searches English keywords, infers terminology from Latin roots, and integrates the result in a diagram. These coordinated resources form a crosslinguistic repertoire.",
  },
  "Folk-theoretical linguistic construct": {
    plain: "普通人在日常生活中形成的语言分类观念，不一定符合语言学分析。",
    kind: "生活例子",
    exampleZh: "居民说‘我们村讲的是土话，不算真正的语言’，把有完整规则的变体降为‘不正规说法’。这种日常分类影响态度和政策，却不是由结构证据自然得出的科学结论。",
    exampleEn: "Residents say their village speech is ‘only slang, not a real language,’ despite its systematic structure. The everyday classification shapes attitudes and policy but is a folk-theoretical construct rather than a structural finding.",
  },
  "Language crossing": {
    plain: "说话者使用通常被认为属于另一个、自己并非成员的群体的语言或风格。",
    kind: "生活例子",
    exampleZh: "一名不属于当地毛利社群的学生在同伴面前使用毛利青年风格来表现酷。关键问题不是会不会说，而是他跨入了与他人族群身份相连的资源，可能引发认同或挪用争议。",
    exampleEn: "A student who is not Māori uses a Māori youth style to appear cool among peers. The issue is crossing into resources associated with another group, raising questions of affiliation and appropriation.",
  },
  "Language brokering": {
    plain: "懂两种语言的人在现实事务中替别人传递、解释并协调信息。",
    kind: "生活例子",
    exampleZh: "租房签约时，双语邻居不只逐句翻译，还向房东解释家庭习惯、向租客说明押金规则，并帮助双方确认误解。这个中介过程比单纯文字翻译更广。",
    exampleEn: "During a rental agreement, a bilingual neighbor translates, explains family practices to the landlord, clarifies deposit rules to the tenant, and resolves misunderstandings. The brokering extends beyond word-for-word translation.",
  },
  "Child language brokering": {
    plain: "儿童或青少年在家庭与学校、医院、商店等机构之间替成年人处理跨语言事务。",
    kind: "生活例子",
    exampleZh: "十二岁的女儿陪母亲看医生，解释症状、填写表格，还判断哪些敏感信息需要婉转表达。她既翻译又承担决策和情感责任，这就是儿童语言中介。",
    exampleEn: "A twelve-year-old accompanies her mother to a doctor, explains symptoms, fills in forms, and decides how to phrase sensitive information. She translates while carrying decision-making and emotional responsibility as a child language broker.",
  },
};
