import { useState } from "react";
import type { CompanionBook,CompanionChapter } from "./companionBooks";

export default function CompanionBookReader({book}:{book:CompanionBook}){
 const [unit,setUnit]=useState("all"); const [selected,setSelected]=useState<CompanionChapter|null>(null);
 const units=[...new Set(book.chapters.map(c=>c.unit))];
 const questions=(c:CompanionChapter)=>[
  {zh:`第 ${c.chapter||"导论"} 章的核心贡献是什么？`,en:`What is the central contribution of ${c.chapter?`Chapter ${c.chapter}`:"the General Introduction"}?`,azh:c.focusZh,aen:c.focusEn},
  {zh:"如何把本章框架转化为可观察的研究或专业判断？",en:"How can this chapter’s framework become an observable research or professional judgment?",azh:"明确研究对象、分析单位、所需证据与可能反例；再说明结论能支持到哪一层，不能从相关性直接跳到机制或规范判断。",aen:"Specify the object, unit of analysis, required evidence and possible counterevidence; then bound the inference rather than jumping from association to mechanism or prescription."},
  {zh:"对本章最强的 rebuttal 是什么？作者还可以守住什么？",en:"What is the strongest rebuttal, and what can the author still defend?",azh:`最强质疑是：${c.criticalZh} 即使接受这项批评，本章仍可作为提出问题与组织证据的框架，但其结论必须缩小到资料真正支持的范围。`,aen:`The strongest objection is that ${c.criticalEn.charAt(0).toLowerCase()+c.criticalEn.slice(1)} Even after accepting this criticism, the chapter can remain a framework for asking questions and organizing evidence, provided its claims are narrowed to what the data support.`}
 ];
 return <main><header className="masthead"><a className="brand" href="./"><span className="brand-mark">TL</span><span>{book.shortTitle} · Critical Reading Guide</span></a><nav><a href="./">概念百科</a><a href="handbook.html">Translanguaging</a><a href="#chapters">章节目录</a></nav></header>
 <section className="companion-hero"><span>BOOK READING LAB</span><h1>{book.title}</h1><p>{book.subtitle}</p><div><p>{book.centralZh}</p><p lang="en">{book.centralEn}</p></div></section>
 <section className="companion-overview"><div><span>WHOLE-BOOK ORIENTATION</span><h2>总体导读<br/><em>What to read</em></h2></div><article><b>核心阅读 / Essential route</b><strong>{book.essential}</strong><p>先读核心路线建立全书骨架，再按下方专题单元扩展。每章先重建论证，再审查证据，最后提出最强反驳。</p><p lang="en">Read the essential route first, then expand by thematic unit. Reconstruct each argument, audit its evidence, and only then formulate the strongest rebuttal.</p></article><article><b>掌握标准 / Mastery</b><p>能够解释本章的独特贡献、把概念操作化，并说明反对意见后哪些主张仍然成立。</p><p lang="en">Explain each chapter’s distinctive contribution, operationalize its concepts, and identify what survives the strongest objection.</p></article></section>
 <section className="companion-chapters" id="chapters"><div className="unit-tabs"><button className={unit==="all"?"active":""} onClick={()=>setUnit("all")}>全部 / All</button>{units.map(u=><button key={u} className={unit===u?"active":""} onClick={()=>setUnit(u)}>{u}</button>)}</div><div className="chapter-grid">{book.chapters.filter(c=>unit==="all"||c.unit===unit).map(c=><article className="chapter-card" key={c.chapter}><div><span>{c.chapter?`CHAPTER ${c.chapter}`:"GENERAL INTRODUCTION"}</span><b>{c.unit}</b></div><h3>{c.title}</h3><p>{c.focusZh}</p><button onClick={()=>setSelected(c)}>打开导读 / Open guide →</button></article>)}</div></section>
 {selected&&<div className="modal-backdrop" role="presentation" onMouseDown={()=>setSelected(null)}>
  {/* eslint-disable-next-line jsx-a11y/no-noninteractive-element-interactions */}
  <article className="modal" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><span className="entry-no">{selected.chapter?`CHAPTER ${selected.chapter}`:"GENERAL INTRODUCTION"} · {selected.unit}</span><div className="bilingual-heading"><h2>{selected.title}</h2></div><section className="reading-purpose"><span>GUIDED READING</span><h3>本章要掌握什么？ / What must you master?</h3><p>{selected.focusZh}</p><p className="parallel-english" lang="en">{selected.focusEn}</p></section><section className="critical-rebuttal"><span>CRITICAL REBUTTAL</span><h3>不要轻易接受什么？ / What should you resist?</h3><p>{selected.criticalZh}</p><p lang="en">{selected.criticalEn}</p></section><section className="doctoral-seminar" lang="en"><span>DOCTORAL SUPERVISOR’S SEMINAR</span><h3>Now let me teach this chapter.</h3><p>{selected.focusEn} The doctoral task is to reconstruct the chapter charitably before testing whether its categories, evidence and causal claims travel beyond the cases presented.</p><aside><b>Your doctoral challenge</b><p>{selected.criticalEn}</p></aside></section><section className="chapter-questions"><span>BILINGUAL QUESTIONS</span><h3>问题 / Questions</h3><ol>{questions(selected).map((q,i)=><li key={q.zh}><b>{String(i+1).padStart(2,"0")}</b><div><p>{q.zh}</p><p className="parallel-english" lang="en">{q.en}</p></div></li>)}</ol></section><section className="answer-key"><span>ANSWER KEY · 放在最后</span><h3>参考答案 / Defensible Answers</h3><details><summary>完成问题后展开 / Open after answering</summary><ol>{questions(selected).map((q,i)=><li key={q.azh}><b>问题 {i+1} / Question {i+1}</b><p>{q.azh}</p><p className="parallel-english" lang="en">{q.aen}</p></li>)}</ol></details></section></article>
 </div>}
 <footer><span>{book.title}</span><p>Read · Question · Rebut · Rebuild</p><a href="./">返回百科 →</a></footer></main>
}
