export type CompanionChapter={chapter:number;title:string;unit:string;focusZh:string;focusEn:string;criticalZh:string;criticalEn:string};
export type CompanionBook={id:string;shortTitle:string;title:string;subtitle:string;centralZh:string;centralEn:string;essential:string;chapters:CompanionChapter[]};
const c=(chapter:number,title:string,unit:string,focusZh:string,focusEn:string,criticalZh:string,criticalEn:string):CompanionChapter=>({chapter,title,unit,focusZh,focusEn,criticalZh,criticalEn});

export const sociolinguisticsBook:CompanionBook={id:"sociolinguistics",shortTitle:"Sociolinguistics",title:"The Guidebook to Sociolinguistics",subtitle:"Allan Bell · 2014 · 12 chapters",centralZh:"语言如何构成社会，而社会又如何组织语言？本书把宏观的多语、语言迁移与政策，连接到微观的互动、变异、风格和身份，并把研究方法嵌入每一章。",centralEn:"How does language constitute society, and how does society organize language? Bell connects multilingualism, shift and policy with interaction, variation, style and identity, embedding research practice throughout.",essential:"1 → 5 → 6 → 7 → 10 → 11 → 12",chapters:[
c(1,"What Are Sociolinguistics?","A · Field map","界定 language、a language 与 sociolinguistics，并辨认宏观、互动与变异三条传统。","Define language, a language and sociolinguistics, then map the macro, interactional and variationist traditions.","任何学科地图都会制造中心与边缘；检查 Bell 纳入或排除了哪些语言社会问题。","Every disciplinary map constructs a center and a margin; examine which language-social problems Bell includes or excludes."),
c(2,"A Profusion of Languages","B · Multilingual worlds","比较双语／多语的六个维度、调查方法与人口普查如何把复杂实践变成类别。","Compare dimensions of bilingualism and examine how surveys and censuses turn complex practice into categories.","自报语言能力和国家语言分类可能把制度标签误当作个体实际资源。","Self-reports and census categories may mistake institutional labels for speakers’ actual resources."),
c(3,"Language Shift and Maintenance","B · Multilingual worlds","理解语言功能、代际迁移、维持与复兴，并以 Māori 案例连接理论与政策。","Explain domains, intergenerational shift, maintenance and revitalization through the Māori case.","语言数量指标可能遮蔽使用质量、权力和社区目标；复兴不只是增加会说者。","Speaker counts may obscure quality of use, power and community aims; revitalization is not merely increasing numbers."),
c(4,"Language Birth and Death","B · Multilingual worlds","连接 pidgin、creole、连续体、语言濒危和语言死亡的社会与结构过程。","Connect pidginization, creolization, continua, endangerment and death as social and structural processes.","“出生／死亡”隐喻会把殖民、暴力和分类政治自然化，也可能把 creole 当作异常语言。","Birth/death metaphors can naturalize colonial violence and classification and can exceptionalize creoles."),
c(5,"Codes and Choices","C · Interaction","掌握 variety、code、repertoire、speech community、diglossia 与 code-switching 的关系。","Relate variety, code, repertoire, speech community, diglossia and code-switching.","“选择”可能暗示说者完全自由；实际选择受到能力、制度、受众与惩罚约束。","Choice can imply unconstrained agency, although competence, institutions, audiences and sanctions delimit it."),
c(6,"Situated Language","C · Interaction","用 domain、ethnography of communication、audience、speech act 与 interactional sociolinguistics 分析情境。","Analyze situations through domains, ethnography of communication, audience, speech acts and interactional sociolinguistics.","“context”不能成为事后解释一切的背景筐；必须说明哪些情境要素具有可观察作用。","Context must not become an after-the-fact container; specify which contextual features have observable effects."),
c(7,"Variation in Language","D · Variation","理解社会阶级、族裔、性别与语言变量的定量关系，以及经典变异研究如何建立证据。","Understand quantitative relations among linguistic variables, class, ethnicity and gender in classic variationist work.","相关性不等于社会机制；预设人口类别也可能重演本应解释的身份边界。","Correlation is not a social mechanism, and predefined demographic categories may reproduce the identities under explanation."),
c(8,"Language in Time","D · Variation","区分 real time 与 apparent time，并连接声音变化、市场、网络和社群。","Distinguish real time from apparent time and connect sound change with markets, networks and communities.","年龄分布未必代表历史变化，也可能是年龄分级；网络模型也不应替代制度与政治经济。","Age distributions may reflect age grading rather than change, while network models should not replace institutions and political economy."),
c(9,"Language in Space","D · Variation","从 dialectology 进入空间生产、方言接触、新方言形成、消亡与 linguistic landscape。","Move from dialectology to produced space, dialect contact, new-dialect formation, loss and linguistic landscapes.","地图上的线会把渐变与流动固化；空间不是中性容器，而是由迁移、资本与边界制度制造。","Map lines can freeze continua and mobility; space is produced by migration, capital and border regimes."),
c(10,"Valuing Language","E · Meaning and power","理解语言意识形态、态度、变量评价、indexical cycle 与语言歧视。","Explain ideology, attitudes, variable evaluation, the indexical cycle and linguistic discrimination.","态度实验可能测到实验者制造的口音类别；指数意义也不是对所有听者稳定一致。","Attitude experiments may measure researcher-produced accent categories, while indexical meanings are not stable for every listener."),
c(11,"Styling Language and Identities","E · Meaning and power","比较 attention-to-speech、audience design、referee design 与身份表演。","Compare attention-to-speech, audience design, referee design and the performance of identity.","风格不是完全自由的身份消费；可用资源、可相信度与挪用后果分配不均。","Style is not free identity consumption; resources, credibility and the costs of appropriation are unequally distributed."),
c(12,"Theory and Engagement","F · Synthesis","综合社会在社会语言学中的位置、结构与能动性，并评价 engaged sociolinguistics。","Synthesize the place of the social, structure and agency, and evaluate engaged sociolinguistics.","参与和公共介入并不自动产生更真或更正义的研究；仍需透明证据与问责。","Engagement does not automatically make research truer or more just; evidence and accountability remain necessary.")
]};

export const appliedBook:CompanionBook={id:"applied-linguistics",shortTitle:"Applied Linguistics",title:"The Handbook of Applied Linguistics",subtitle:"Davies & Elder · 2004 · General Introduction + 32 chapters",centralZh:"应用语言学是把语言学知识用于现实问题，还是从现实问题出发建构自己的跨学科知识？全书以 Linguistics-Applied 与 Applied-Linguistics 的张力组织答案。",centralEn:"Does applied linguistics apply linguistic knowledge to practical problems, or build interdisciplinary knowledge from problems themselves? The volume organizes its answer through the tension between Linguistics-Applied and Applied-Linguistics.",essential:"Introduction → 1 → 5 → 16 → 19 → 20 → 22 → 24 → 30 → 31 → 32",chapters:[
c(0,"General Introduction: Applied Linguistics—Subject to Discipline?","A · Field architecture","理解 applied linguistics 的学科对象、专业边界和 L-A／A-L 两种方向。","Understand the object, disciplinary boundaries and L-A/A-L orientations of applied linguistics.","二分法有导航价值，却可能掩盖多数研究在理论与问题之间来回移动。","The binary is useful for navigation but may hide how research iterates between theory and problems."),
c(1,"Language Descriptions","B · Linguistic resources","理解语音、语法和类型描述如何成为应用工作的基础。","Understand how phonological, grammatical and typological descriptions support applied work.","描述从不完全中性；选择何种单位与标准会影响教育和政策后果。","Description is never fully neutral; units and norms have educational and policy consequences."),
c(2,"Lexicography","B · Linguistic resources","考察词典如何选择词目、定义意义、标注规范并服务不同用户。","Examine how dictionaries select entries, define meanings, mark norms and serve users.","词典既记录也规范；语料频率不能独自决定污名、冒犯或使用建议。","Dictionaries both record and regulate; frequency alone cannot settle stigma, offense or usage advice."),
c(3,"Second Language Acquisition and Ultimate Attainment","C · Learning evidence","理解年龄、关键期与终极成就证据。","Evaluate evidence on age, critical periods and ultimate attainment.","接近母语者的结果指标可能把 native speaker 当作天然终点并忽略多语能力。","Native-like outcomes may naturalize the native speaker as the endpoint and obscure multilingual competence."),
c(4,"Language Corpora","B · Linguistic resources","掌握语料库的代表性、频率、搭配与模式发现。","Understand corpus representativeness, frequency, collocation and pattern discovery.","大型语料不等于代表性；可数字化、可收集的语言常被误当作语言本身。","A large corpus is not necessarily representative; collectible language is often mistaken for language itself."),
c(5,"Discourse Analysis","B · Linguistic resources","比较话语分析的问题、资料与教育应用。","Compare discourse-analytic questions, data and educational applications.","discourse analysis 是多传统集合；若不明确单位与推论，解释容易选择性过强。","Discourse analysis contains divergent traditions; without explicit units and inference, interpretation can become selective."),
c(6,"British Sign Language","B · Linguistic resources","把 BSL 视为完整语言系统，并连接结构、诗性、教育和解释服务。","Treat BSL as a full linguistic system and connect structure with poetics, education and interpreting.","不能把手语只当作证明语言普遍性的素材；聋人知识与语言权利必须居中。","Sign language must not serve merely as evidence for universals; Deaf knowledge and language rights must remain central."),
c(7,"Assessing Language Attitudes","D · Society and institutions","理解 matched-guise／speaker evaluation 的设计与推论。","Understand matched-guise and speaker-evaluation designs and their inferential logic.","实验控制可能制造不自然声音，态度评分也不能直接等同现实歧视行为。","Experimental control may create artificial voices, and ratings do not directly equal discriminatory behavior."),
c(8,"Language Attrition","C · Learning evidence","区分语言流失、暂时提取困难、接触减少与身份变化。","Distinguish attrition from retrieval difficulty, reduced exposure and identity change.","把变化称为 loss 可能采用单语缺陷尺度并忽视重组与适应。","Calling change loss may impose a monolingual deficit scale and overlook reorganization and adaptation."),
c(9,"Language, Thought, and Culture","D · Society and institutions","评价语言相对论、文化意义与学习者主体性的关系。","Evaluate linguistic relativity, cultural meaning and learner subjectivity.","相关性与翻译困难不足以证明语言决定思想；culture 也不能被本质化。","Correlation and translation difficulty do not prove linguistic determinism, and culture must not be essentialized."),
c(10,"Conversation Analysis","B · Linguistic resources","理解序列组织、话轮、修复与参与者导向。","Understand sequence organization, turn-taking, repair and participant orientation.","严格限制于可见参与者导向可能低估制度、种族和历史结构。","Restricting analysis to displayed orientations may understate institutions, race and history."),
c(11,"Language and the Law","D · Society and institutions","分析法律语言、证词、解释、权利告知和法庭不平等。","Analyze legal language, testimony, interpreting, rights cautions and courtroom inequality.","语言专家不能把概率证据包装成身份确定性，公平也不只是简化文本。","Experts must not turn probabilistic evidence into identity certainty; fairness is more than plain wording."),
c(12,"Language and Gender","D · Society and institutions","从差异模型转向权力、互动与性别实践。","Move from difference models toward power, interaction and gendered practice.","男女二分会抹去交叉性与非二元经验；局部模式不能普遍化。","Binary categories erase intersectionality and nonbinary experience; local patterns cannot be universalized."),
c(13,"Stylistics","B · Linguistic resources","连接语言形式、文学解释、读者反应与教学。","Connect linguistic form, literary interpretation, reader response and teaching.","形式特征不能机械产生文学意义；分析者选择仍需论证。","Formal features do not mechanically produce literary meaning; analysts must justify selection and interpretation."),
c(14,"Language and Politics","D · Society and institutions","研究政治命名、修辞、民族国家与语言意识形态。","Study political naming, rhetoric, nation-states and language ideology.","只分析政治文本可能忽视传播基础设施、物质政策与受众行动。","Textual analysis alone may neglect media infrastructure, material policy and audience action."),
c(15,"World Englishes","D · Society and institutions","理解英语传播、本土化、规范与所有权。","Understand the spread, localization, norms and ownership of English.","国家化 varieties 模型可能低估内部差异、跨国流动和不平等英语。","Nation-based variety models may understate internal diversity, mobility and unequal Englishes."),
c(16,"The Philosophy of Applied Linguistics","A · Field architecture","追问知识、问题、价值与实践之间的哲学关系。","Interrogate relations among knowledge, problems, values and practice.","哲学反思若不改变研究选择，可能只是抽象自我描述。","Philosophical reflection can become abstract self-description unless it changes research decisions."),
c(17,"The Native Speaker in Applied Linguistics","E · Applied problems","拆解 native speaker 的语言能力、身份与制度权威。","Disentangle native-speaker competence, identity and institutional authority.","揭示神话不等于该类别在考试、就业与社群身份中没有现实效力。","Exposing a myth does not erase the category’s real effects in testing, employment and community identity."),
c(18,"Language Minorities","E · Applied problems","比较少数语言、权利、人口、身份与国家政策。","Compare minority languages, rights, demography, identity and state policy.","minority 不是纯数量概念；国家分类也可能制造它声称管理的少数地位。","Minority is not simply numerical; state classification may produce the status it claims to manage."),
c(19,"Research Methods for Applied Linguistics","F · Research and critique","掌握研究问题、设计、质性／量化与研究质量标准。","Master research questions, design, qualitative/quantitative approaches and quality standards.","方法清单不能替代问题—证据对齐；mixed methods 也不自动更强。","Method inventories cannot replace question-evidence alignment, and mixed methods are not automatically superior."),
c(20,"Second Language Learning","C · Learning evidence","建立二语学习的过程、条件与教学关联总体模型。","Build an overall model of second-language learning processes, conditions and pedagogical links.","总体模型可能把不同理论并列而未解决冲突，也容易把学习等同课堂进步。","Synthetic models may juxtapose unresolved theories and equate learning with classroom progress."),
c(21,"Individual Differences in Second Language Learning","C · Learning evidence","理解 aptitude、motivation、strategy、belief 与测量。","Understand aptitude, motivation, strategies, beliefs and their measurement.","个体差异研究可能把制度问题心理化，并把不稳定构念当固定特质。","Individual-difference research may psychologize structural problems and treat unstable constructs as traits."),
c(22,"Social Influences on Language Learning","C · Learning evidence","把身份、社群、机会和社会环境放回学习理论。","Restore identity, community, opportunity and social context to theories of learning.","social 不能只是变量列表；需要说明结构如何通过具体机制改变参与与发展。","The social cannot be a list of variables; mechanisms linking structure to participation and development are needed."),
c(23,"Literacy Studies","E · Applied problems","从技能模型转向 literacy as social practice，并连接教育与发展。","Move from skills models to literacy as social practice and connect education with development.","反对单一技能观不应否认解码、流利度等可教学能力的实际价值。","Rejecting autonomous skills models should not deny the practical value of teachable decoding and fluency."),
c(24,"Fashions in Language Teaching Methodology","G · Professional practice","理解教学法潮流、方法兴衰与课堂适配。","Understand methodological fashions, their rise and decline, and classroom adaptation.","批判 fashions 不能滑向“什么都有效”；主张仍需机制与比较证据。","Critiquing fashions must not become ‘anything works’; claims still require mechanisms and comparative evidence."),
c(25,"Computer Assisted Language Learning (CALL)","G · Professional practice","评价技术 affordance、学习理论、任务与教师角色。","Evaluate technological affordances, learning theory, tasks and teacher roles.","技术新颖性不等于学习增益；还要看数字鸿沟、平台数据与替代成本。","Technical novelty is not learning gain; examine access, platform data and opportunity costs."),
c(26,"Language Teacher Education","G · Professional practice","连接教师知识、信念、身份、实践与专业发展。","Connect teacher knowledge, beliefs, identity, practice and professional development.","培训时数不是教师学习；改革若忽略工作条件，责任会被转嫁给个人教师。","Training hours are not teacher learning; reforms that ignore working conditions individualize responsibility."),
c(27,"The Practice of LSP","G · Professional practice","理解 needs analysis、专业语域、课程与利益相关者。","Understand needs analysis, specialized registers, curricula and stakeholders.","雇主需求不应自动凌驾学习者未来、专业伦理与批判能力。","Employer needs should not automatically override learners’ futures, professional ethics and critical agency."),
c(28,"Bilingual Education","G · Professional practice","比较双语教育模式、目标、政策与结果。","Compare bilingual-education models, goals, policies and outcomes.","项目标签不能预测课堂现实；学业结果也需与语言权利和身份后果并看。","Program labels do not predict classroom reality; outcomes must include rights and identity, not only attainment."),
c(29,"Language Maintenance","E · Applied problems","分析代际传承、领域、社群资源与反转语言迁移。","Analyze intergenerational transmission, domains, community resources and reversing shift.","maintenance 容易暗示静态保存；社群可能追求变化中的延续而非语言纯化。","Maintenance can imply static preservation; communities may seek continuity through change rather than purity."),
c(30,"Language Planning as Applied Linguistics","E · Applied problems","理解 status、corpus、acquisition planning 与政策实施。","Understand status, corpus and acquisition planning and policy implementation.","规划者常高估自上而下意图；政策意义会被机构与社区重新解释。","Planners often overestimate top-down intention; institutions and communities reinterpret policy."),
c(31,"Language Testing","G · Professional practice","掌握 construct、validity、criterion 与测试后果。","Master constructs, validity, criteria and the consequences of testing.","信度不能补救错误构念；社会后果也不是技术效度之外的附加项。","Reliability cannot rescue a wrong construct, and consequences are not external to validity."),
c(32,"Critical Applied Linguistics","F · Research and critique","理解 critical 的多种形式及权力、知识与实践的关系。","Understand forms of the critical and relations among power, knowledge and practice.","批判姿态可能成为身份标签；必须说明证据、行动对象和可反驳条件。","Criticality can become an identity label; specify evidence, targets of action and conditions of refutation.")
]};

export const genAIBook:CompanionBook={id:"genai-language-education",shortTitle:"Language Education × GenAI",title:"Rethinking Language Education in the Age of Generative AI",subtitle:"Tian & Wang · 2025 · Introduction + 11 chapters",centralZh:"当生成式 AI 已能翻译、对话、反馈与生成文本时，语言教育还应以个人独立产出和接近母语者的熟练度为中心吗？本书要求我们重新定义学习目的、人机协作、真实性、评估、教师专业性与批判性 AI 素养。",centralEn:"When generative AI can translate, converse, provide feedback and produce texts, should language education still center independent production and native-like proficiency? The volume rethinks purposes, human–AI collaboration, authenticity, assessment, teacher expertise and critical AI literacy.",essential:"Foreword → Introduction → 1 → 2 → 3 → 5 → 7 → 10 → 11",chapters:[
c(0,"Introduction","A · Reframing the field","建立生成式 AI 与语言教育的概念、研究和实践议程，并把创新与批判、伦理、责任连接起来。","Establish a conceptual, empirical and practical agenda that connects innovation with critical, ethical and responsible language education.","“重新思考”不能只意味着把新工具加入旧课堂；必须说明学习目的、权力或评价发生了什么变化。","Rethinking cannot mean inserting new tools into old classrooms; it must specify changes in educational purposes, power or assessment."),
c(1,"A Five-Ecosystem Approach to Generative AI in Language Classrooms","B · Conceptual ecosystems","用五个相互作用的生态系统分析学习者、教师、工具、机构与更广社会环境，而非孤立评价 AI 工具。","Use five interacting ecosystems to analyze learners, teachers, tools, institutions and wider social environments rather than evaluating AI in isolation.","生态隐喻容易把权力冲突描述成自然互依；需要指出谁控制模型、数据、规则与成本。","Ecological metaphors may naturalize power conflicts as interdependence; identify who controls models, data, rules and costs."),
c(2,"Language Teacher Preparation for an AI World: A Human Ecological Perspective","B · Conceptual ecosystems","重新定义教师 AI 能力：不只是 prompt 技巧，而是判断、课程设计、伦理、批判素养与持续适应。","Redefine teacher AI competence beyond prompting to judgment, curriculum design, ethics, critical literacy and continuing adaptation.","把持续适应要求压给教师个人，会掩盖培训时间、基础设施、劳动条件与机构责任。","Making individual teachers continuously adapt can obscure training time, infrastructure, labor conditions and institutional responsibility."),
c(3,"Human–AI Teaming: Indigenous Perspectives","C · Evidence and equity","从泰国、菲律宾和印度尼西亚的 Indigenous perspectives 检查 human–AI collaboration 的文化前提。","Use Indigenous perspectives from Thailand, the Philippines and Indonesia to examine the cultural assumptions of human–AI collaboration.","“Indigenous perspective”不能成为多样性标签；研究须交代知识所有权、数据主权、翻译与社群决策权。","Indigenous perspective must not become a diversity label; address knowledge ownership, data sovereignty, translation and community authority."),
c(4,"Modality or Authenticity? Authentic versus AI-Generated Texts","C · Evidence and equity","区分文本模态、来源真实性与学习者投入，检验 AI 生成材料是否改变 engagement。","Separate modality, source authenticity and learner engagement when testing AI-generated versus authentic texts.","authentic／AI-generated 二分可能不稳定；真实材料也被编辑，AI 文本也可能进入真实社会实践。","The authentic/AI-generated binary is unstable: authentic materials are curated, while AI texts may participate in real social practice."),
c(5,"ChatGPT-3 Policies in the Making","C · Evidence and equity","分析高校 AI 政策如何看见或忽略国际学生的多语写作、语言支持与公平需要。","Analyze how institutional AI policies recognize or overlook international students’ multilingual writing, language support and equity needs.","诚信政策若假设所有学生拥有相同英语资源、技术理解和申诉能力，会制造新的不平等。","Integrity policies create new inequities when they assume equal English resources, technical understanding and capacity to appeal."),
c(6,"Using Large Language Models for Oral Proficiency Interview Practice","C · Evidence and equity","评价 LLM 模拟口试在练习量、反馈、焦虑、效度与口语发展方面的作用。","Evaluate LLM-supported oral-interview practice in terms of practice volume, feedback, anxiety, validity and speaking development.","系统能模拟测试格式，不等于能准确判断语用、互动能力或现实口语；练习收益也不能等同真实测评效度。","Simulating a test does not guarantee valid judgment of pragmatics, interaction or real-world speaking, and practice gains do not establish assessment validity."),
c(7,"Teaching Global Englishes with ChatGPT","D · Pedagogical redesign","用 ChatGPT 模拟和分析英语变体，发展 Global Englishes 意识并挑战唯一标准英语。","Use ChatGPT to model and analyze English varieties, develop Global Englishes awareness and challenge a single standard.","LLM 可能刻板化、编造或等级化英语变体；生成内容必须回到真实社群资料核验。","LLMs may stereotype, fabricate or rank English varieties; outputs must be checked against community-grounded data."),
c(8,"ChatGPT in Postsecondary Pathways Programs","D · Pedagogical redesign","理解国际学生衔接课程中 AI 使用、教师判断、学术语言与升学准备的张力。","Examine tensions among AI use, teacher judgment, academic language and progression in pathways programs.","“为大学做好准备”可能只是训练学生适应既有单语规范，而没有质疑这些规范是否公平或仍然有效。","Readiness may simply train students to fit existing monolingual norms without asking whether those norms remain fair or useful."),
c(9,"AI-Integrated English Language Teaching in K–12 Classrooms","D · Pedagogical redesign","从韩国 K–12 情境理解课程、年龄、教师支持、平台与国家政策如何共同塑造 AI 整合。","Use the South Korean K–12 context to examine how curriculum, age, teacher support, platforms and national policy shape AI integration.","单一国家案例不可直接普遍化；儿童数据、商业平台依赖和家校差异必须成为核心评价指标。","One national case cannot be generalized directly; children’s data, platform dependence and home–school inequalities must be central criteria."),
c(10,"AI Chatbots in L2 University Courses","D · Pedagogical redesign","利用 chatbot 发展语用能力与 critical digital literacy，同时让学生分析 AI 的交际偏差。","Use chatbots to develop pragmatic competence and critical digital literacy while analyzing AI’s communicative biases.","流畅、礼貌的 AI 对话可能把主流语用规范包装成普遍规则，并减少与真实人的风险性协商。","Fluent, polite AI dialogue may universalize dominant pragmatic norms and reduce consequential negotiation with real people."),
c(11,"Scaffolded Integration of ChatGPT for Language and Culture Learning","D · Pedagogical redesign","通过分阶段支架安排提示、比较、核验、修订与反思，使 AI 参与而不替代学习者判断。","Use staged scaffolding for prompting, comparison, verification, revision and reflection so AI participates without replacing learner judgment.","scaffolding 若只教更有效地产出答案，仍可能强化依赖；必须逐步转移判断责任并检验无 AI 时的能力。","Scaffolding can reinforce dependence if it only improves output; responsibility for judgment must transfer to learners and be tested without AI.")
]};
