import { useEffect, useMemo, useState } from "react";

type RecordState={book:string;chapter:string;claim:string;evidence:string;rebuttal:string;reply:string;position:string;dissertation:string;next:string};
type Paper={id:string;title:string;author?:string;year?:number;abstract?:string;relevance?:string;doi?:string};
type SourceRole="supports"|"complicates"|"challenges"|"method";
type SelectedSource={paper:Paper;role:SourceRole};
type HearingAnswers=Record<string,string>;
const empty:RecordState={book:"The Handbook of Translanguaging",chapter:"",claim:"",evidence:"",rebuttal:"",reply:"",position:"",dissertation:"",next:""};
const books=["The Handbook of Translanguaging","The Guidebook to Sociolinguistics","The Handbook of Applied Linguistics","Rethinking Language Education in the Age of Generative AI"];
const fields=[
 ["claim","1 · Reconstruct the argument","核心主张是什么？用最公平的方式复述。","What is the central claim? Reconstruct it charitably."],
 ["evidence","2 · Audit the evidence","作者凭什么这样说？证据与推论之间有没有跳跃？","What warrants the claim? Where does the inference outrun the evidence?"],
 ["rebuttal","3 · Form the strongest objection","最强反驳是什么？不要只挑措辞问题。","What is the strongest substantive objection—not a complaint about wording?"],
 ["reply","4 · Steelman the author’s reply","如果作者在场，他／她会如何回应？","How would the author answer if they were in the room?"],
 ["position","5 · State your position","你的暂时立场是什么？成立条件和边界是什么？","What is your provisional position, with conditions and limits?"],
 ["dissertation","6 · Transfer to the dissertation","这能进入论文哪一部分？支持、修正还是挑战哪个论点？","Where can this enter your dissertation, and what claim does it support, revise, or challenge?"],
 ["next","7 · Build the next reading move","下一步要追哪篇文献、哪种证据或哪个反例？","What source, evidence, or counterexample should you pursue next?"],
] as const;
const scholars=[
 {group:"本体与理论",name:"Li Wei",key:"Translanguaging Space · practical theory",q:"你的分析是否真的从意义建构出发，还是先用‘中文／英文’把数据切开，再贴上 translanguaging 标签？",a:"可辩护的回答：我把具名语言作为社会制度事实，但分析单位是参与者调动的语言、身体、物质与数字资源；类别来自互动证据，而非预先划界。"},
 {group:"本体与理论",name:"Ofelia García",key:"unitary repertoire · bilingual education",q:"你的研究是在帮助双语者学习，还是仍然要求他们服从学校规定的单语规范？",a:"可辩护的回答：我区分学习者的整体 repertoire 与学校对具名语言的配置，并分析教学设计何时扩大能动性、何时只是更温和地维持单语秩序。"},
 {group:"本体与理论",name:"Suresh Canagarajah",key:"translingual practice · negotiation",q:"意义与规范是在互动中如何协商出来的？不要只告诉我出现了几次语言切换。",a:"可辩护的回答：我追踪参与者如何通过 repair、重述、姿态与跨模态资源共同达成意义，并把‘成功’定义为局部协商结果而非接近母语规范。"},
 {group:"本体与理论",name:"Jasone Cenoz & Durk Gorter",key:"Focus on Multilingualism · pedagogical translanguaging",q:"你是否把自然发生的多语实践与教师有计划的教学策略混为一谈？目标语发展如何被保护？",a:"可辩护的回答：我分别标注 spontaneous 与 planned practices，并检验资源开放是否服务于明确的学习目标，而不预设‘越流动越好’。"},
 {group:"权力与去殖民",name:"Sinfree Makoni & Alastair Pennycook",key:"disinventing languages",q:"你是在解构殖民语言分类，还是把这些分类换一个进步术语重新包装？",a:"可辩护的回答：我会追问语言类别由谁建立、服务何种治理，同时承认这些类别已经产生真实的资源分配后果，不能仅靠话语姿态取消。"},
 {group:"权力与去殖民",name:"Nelson Flores & Jonathan Rosa",key:"raciolinguistic ideologies",q:"问题真的是学生的语言形式，还是听者以种族化标准决定什么算‘合格语言’？",a:"可辩护的回答：我把评价者与制度规范也纳入分析，比较同一实践在不同说话者身上如何被差异化听见，避免把不平等归因于 repertoire 本身。"},
 {group:"权力与去殖民",name:"Ryuko Kubota",key:"race · neoliberalism · critical reflexivity",q:"你的社会正义主张是否浪漫化了多语实践，并忽略阶级、市场价值与研究者自身位置？",a:"可辩护的回答：我不会从‘允许跨语’直接推出赋权，而会检查谁获益、谁承担风险、何种语言资源仍更可兑换，并交代自己的制度位置。"},
 {group:"课堂与教师",name:"Danping Wang",key:"CSL classroom policy · relational pedagogy",q:"在真实中文课堂与机构约束中，教师信念、政策和实践为何不一致？这种变化能否持续？",a:"可辩护的回答：我把 ideology–practice gap 当作研究对象，追踪教师如何在长期关系、招生压力、课程目标与学生反馈中调整实践，而不是把教师分成支持或反对两类。"},
 {group:"课堂与教师",name:"Angela Creese & Adrian Blackledge",key:"flexible bilingual pedagogy · ethnography",q:"课堂中的灵活实践如何被参与者共同建构？你的解释有足够厚的民族志证据吗？",a:"可辩护的回答：我把互动片段放回学校历史、参与者关系和制度话语中，用跨资料证据说明某一资源在当地为何具有特定意义。"},
 {group:"课堂与教师",name:"Kevin Tai",key:"multimodal CA · translanguaging space",q:"你声称的身份、参与或赋权，能否在逐轮互动和多模态细节中看见？",a:"可辩护的回答：我用序列证据展示参与如何发生变化，并把访谈感受作为互补证据，而不是用事后访谈替代课堂过程。"},
 {group:"学习与身份",name:"Jim Cummins",key:"cross-linguistic transfer · identity texts",q:"学习者已有语言知识如何支持新知识发展？开放 repertoire 与学术语言成长之间的机制是什么？",a:"可辩护的回答：我提出可观察的中介链：已有资源降低处理负荷、支持概念表征或身份投入，继而促成目标任务表现；并检验替代解释。"},
 {group:"学习与身份",name:"Bonny Norton & Ron Darvin",key:"investment · identity · capital",q:"学生为什么在这个时刻投入或拒绝参与？语言选择如何关联资本、身份和意识形态？",a:"可辩护的回答：我不把参与不足解释为动机缺失，而分析学习者预期可获得的象征／物质回报，以及课堂位置是否允许其想象身份出现。"},
 {group:"学习与身份",name:"Merrill Swain",key:"languaging · collaborative dialogue",q:"跨语实践具体在何时推动了注意、假设检验或知识共同建构？",a:"可辩护的回答：我定位 LRE、解释请求、reformulation 与共同解决的序列，区分单纯任务管理和真正产生学习机会的 languaging。"},
 {group:"学习与身份",name:"James Lantolf",key:"sociocultural theory · mediation",q:"你所谓的‘中介’是什么过程，而不是一个万能标签？能力如何从协作调节转向自我调节？",a:"可辩护的回答：我明确符号／他人／工具中介的对象与时间尺度，并寻找从 other-regulation 到 self-regulation 的变化证据。"},
 {group:"评估与制度",name:"Elana Shohamy",key:"critical language testing · policy power",q:"这项评估表面测语言，实际上在执行什么政策、分配什么机会？",a:"可辩护的回答：我把分数之外的使用、制裁、守门与反拨纳入效度论证，说明评估后果不是附录，而是制度功能的一部分。"},
 {group:"评估与制度",name:"Tim McNamara",key:"social dimensions of assessment",q:"被测量的是个人能力，还是考生与任务、评价者及制度规范共同形成的表现？",a:"可辩护的回答：我限制对‘能力’的去语境化推断，并说明评分解释依赖的互动条件、身份规范与价值判断。"},
 {group:"数字与 AI",name:"Richard Kern & Steven Thorne",key:"technology-mediated language learning",q:"技术改变了哪一种活动结构和能动性，而不只是让旧任务变得更快？",a:"可辩护的回答：我比较 AI 介入前后的参与角色、时间性、反馈回路与符号资源，分析人机共演化，而不把工具效果当作独立变量神话。"},
 {group:"数字与 AI",name:"Mark Warschauer",key:"digital literacies · access and learning",q:"谁拥有有效使用 AI 的条件？所谓创新是否扩大了新的数字与学术鸿沟？",a:"可辩护的回答：我把 access 拆成设备、技能、语言资本、教学支持与可转化成果，并比较不同学习者实际获得的学习收益。"},
];
const inspirations=[
 {title:"把 MICM 从‘模型名称’变成可证伪机制",from:"CSL peer interaction · LRE · negotiation of meaning",move:"将机制拆成触发条件 → 资源调动 → 协商动作 → 局部结果，并寻找没有产生预期结果的 negative cases。这样它才不只是对课堂片段的漂亮重命名。"},
 {title:"把 ideology–practice gap 改写成教师的制度性调节",from:"EMI · translanguaging · identity · action research",move:"不要只说教师‘信念与实践不一致’。追踪教师如何回应政策、学生需求、专业身份与风险，提出一个随时间变化的调节模型。"},
 {title:"从数字第三空间走向平台化的语言权力",from:"Xiaohongshu · multimodality · identity work",move:"进一步问平台的可见性规则、算法想象和商业化风格如何决定哪些跨语实践更有价值。这样研究会从功能分类进入 platformed sociolinguistics。"},
 {title:"把 vulnerability 与 assessment 串成同一条制度链",from:"teacher vulnerability · institutional discourse · washback",move:"考试和政策不仅塑造学生，也塑造教师可以成为什么样的专业主体。可比较守门性评价如何产生情感劳动、顺从与微观抵抗。"},
 {title:"用 epistemic justice 统一你的分散议题",from:"assessment equity · classroom interaction · AI",move:"共同问题可以是：谁的知识、语言资源和判断被制度承认为有效？这能连接考试、课堂参与和 AI 反馈，但必须为每个场景给出不同的可观察机制。"},
 {title:"把 AI 看作新的参与者，而不是教学工具",from:"generative AI · mediation · language education",move:"研究学习者、教师与模型如何共同分配认识责任：谁提出、谁验证、谁被相信、错误由谁承担。这里可把 mediation、epistemic authority 与 translanguaging 真正连起来。"},
];

export default function DoctoralWorkspace(){
 const [record,setRecord]=useState<RecordState>(()=>{try{const raw=localStorage.getItem("tl-doctoral-record");return raw?{...empty,...JSON.parse(raw)}:empty}catch{return empty}}); const [saved,setSaved]=useState(false);
 const [papers,setPapers]=useState<Paper[]>([]);const [query,setQuery]=useState("");const [libraryState,setLibraryState]=useState<"loading"|"ready"|"error">("loading");
 const [selected,setSelected]=useState<SelectedSource[]>(()=>{try{return JSON.parse(localStorage.getItem("tl-source-constellation")||"[]")}catch{return []}});const [ownPaper,setOwnPaper]=useState(()=>localStorage.getItem("tl-own-paper")||"");const [synthesis,setSynthesis]=useState(()=>localStorage.getItem("tl-synthesis")||"");
 const [scholarGroup,setScholarGroup]=useState("全部");
 const [committee,setCommittee]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem("tl-committee")||'["Li Wei","Ryuko Kubota","Danping Wang","Elana Shohamy"]')}catch{return ["Li Wei","Ryuko Kubota","Danping Wang","Elana Shohamy"]}});
 const [hearingAnswers,setHearingAnswers]=useState<HearingAnswers>(()=>{try{return JSON.parse(localStorage.getItem("tl-hearing-answers")||"{}")}catch{return {}}});
 useEffect(()=>{const controller=new AbortController();fetch("https://gracieme.github.io/research-library/papers.json",{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json()}).then(data=>{setPapers(data);setLibraryState("ready")}).catch(e=>{if(e.name!=="AbortError")setLibraryState("error")});return()=>controller.abort()},[]);
 const completeness=useMemo(()=>Math.round(fields.filter(([key])=>record[key].trim()).length/fields.length*100),[record]);
 const update=(key:keyof RecordState,value:string)=>{setRecord(r=>({...r,[key]:value}));setSaved(false)};
 const save=()=>{localStorage.setItem("tl-doctoral-record",JSON.stringify(record));setSaved(true)};
 const exportMd=()=>{const sources=selected.map(s=>`- **${s.role}:** ${s.paper.title} — ${s.paper.author||""}`).join("\n");const hearing=committee.map(name=>`### ${name}\n\n${hearingAnswers[name]||"—"}`).join("\n\n");const body=`# Doctoral Reading Record\n\n**Book:** ${record.book}\n\n**Chapter:** ${record.chapter||"—"}\n\n## Evidence constellation\n\n**My paper:** ${ownPaper||"—"}\n\n${sources||"—"}\n\n## Synthesis memo\n\n${synthesis||"—"}\n\n## Committee hearing\n\n${hearing||"—"}\n\n${fields.map(([key,title,zh,en])=>`## ${title}\n\n*${zh} / ${en}*\n\n${record[key]||"—"}`).join("\n\n")}`;const blob=new Blob([body],{type:"text/markdown"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`doctoral-reading-${record.chapter||"record"}.md`;a.click();URL.revokeObjectURL(url)};
 const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return papers.slice(0,6);return papers.filter(p=>`${p.title} ${p.author||""} ${p.abstract||""} ${p.relevance||""}`.toLowerCase().includes(q)).slice(0,8)},[papers,query]);
 const persist=(next:SelectedSource[])=>{setSelected(next);localStorage.setItem("tl-source-constellation",JSON.stringify(next))};
 const addSource=(paper:Paper)=>{if(!selected.some(s=>s.paper.id===paper.id))persist([...selected,{paper,role:"complicates"}])};
 const changeRole=(id:string,role:SourceRole)=>persist(selected.map(s=>s.paper.id===id?{...s,role}:s));
 const removeSource=(id:string)=>persist(selected.filter(s=>s.paper.id!==id));
 const toggleCommittee=(name:string)=>{const next=committee.includes(name)?committee.filter(n=>n!==name):committee.length<6?[...committee,name]:committee;setCommittee(next);localStorage.setItem("tl-committee",JSON.stringify(next))};
 const answerHearing=(name:string,value:string)=>{const next={...hearingAnswers,[name]:value};setHearingAnswers(next);localStorage.setItem("tl-hearing-answers",JSON.stringify(next))};
 const hearingScholars=scholars.filter(s=>committee.includes(s.name));
 return <main className="workspace"><header className="masthead"><a className="brand" href="programme.html"><span className="brand-mark">PhD</span><span>博士训练台</span></a><nav><a href="programme.html">当前培养步骤</a><a href="#council">学者委员会</a><a href="#record">研究记录</a></nav></header>
 <section className="workspace-top"><div><span>RESOURCE & DEFENSE ROOM</span><h1>这里是资源室。<br/>培养路径一步一步来。</h1><p>论文库、学者委员会和模拟答辩都保留在这里；如果你还没有明确今天要做什么，请先回到当前培养步骤。</p></div><aside><b>第一次来这里？</b><p>不要一次完成所有模块。培养路径会告诉你当前只需要练哪一种能力。</p><a href="programme.html">进入当前培养步骤 →</a></aside></section>
 <section className="doctoral-cycle"><span>READ</span><i>→</i><span>RECONSTRUCT</span><i>→</i><span>CHALLENGE</span><i>→</i><span>POSITION</span><i>→</i><span>RESEARCH</span><i>→</i><span>DEFEND</span></section>
 <section className="scholar-council" id="council"><div className="council-head"><div><span>SCHOLAR COUNCIL · 学者委员会</span><h2>让不同传统的大佬<br/>同时挑战你的论证。</h2></div><p>以下不是学者原话，而是依据其代表性著作建立的导师式模拟。先读“他／她会追问什么”，自己回答，再展开示范答案；真正的博士立场应当能够同意一部分、反驳一部分。</p></div><div className="council-filters">{["全部",...new Set(scholars.map(s=>s.group))].map(g=><button className={scholarGroup===g?"active":""} onClick={()=>setScholarGroup(g)} key={g}>{g}</button>)}</div><div className="committee-count">已选 {committee.length}/6 位答辩委员 · 点击学者卡片底部加入或移出</div><div className="council-grid">{scholars.filter(s=>scholarGroup==="全部"||s.group===scholarGroup).map(s=><article className={committee.includes(s.name)?"on-committee":""} key={s.name}><small>{s.group}</small><h3>{s.name}</h3><em>{s.key}</em><h4>可能会追问 / Likely challenge</h4><p>{s.q}</p><details><summary>展开导师式示范答案</summary><p>{s.a}</p><b>你的任务：找出这个答案仍然没有解决的一个问题。</b></details><button className="committee-toggle" onClick={()=>toggleCommittee(s.name)}>{committee.includes(s.name)?"移出本次委员会 −":"加入本次委员会 +"}</button></article>)}</div></section>
 <section className="committee-hearing" id="hearing"><div className="hearing-head"><div><span>COMMITTEE HEARING · 模拟答辩</span><h2>同一个论点，接受多种传统的交叉审问。</h2></div><p>先写答案，再看示范。你的目标不是让所有委员满意，而是解释你接受哪些前提、拒绝哪些前提，以及你的证据能把主张推进到哪里。</p></div><label className="hearing-claim"><b>本次要 defend 的论点</b><textarea rows={3} value={record.claim} onChange={e=>update("claim",e.target.value)} placeholder="例如：Translanguaging in EMI classrooms expands students’ epistemic participation…"/></label>{hearingScholars.length===0?<p className="hearing-empty">请从上方至少选择一位答辩委员。</p>:<div className="hearing-questions">{hearingScholars.map((s,i)=><article key={s.name}><span>QUESTION {String(i+1).padStart(2,"0")}</span><h3>{s.name}</h3><small>{s.key}</small>{record.claim.trim()&&<blockquote>针对你的论点：“{record.claim}”</blockquote>}<p>{s.q}</p><label>你的回答 / Your defense<textarea rows={5} value={hearingAnswers[s.name]||""} onChange={e=>answerHearing(s.name,e.target.value)} placeholder="先回答立场、证据、边界，再处理反例。"/></label></article>)}</div>}<section className="hearing-key"><span>MODEL RESPONSES · 答案放在最后</span><details><summary>回答完毕后，展开导师式参考答案</summary>{hearingScholars.map(s=><article key={s.name}><h3>{s.name}</h3><p>{s.a}</p><b>这不是标准答案：你还必须指出它遗漏的证据或前提。</b></article>)}</details></section></section>
 <section className="literature-lab"><div className="lab-intro"><span>EVIDENCE CONSTELLATION · 文献星座</span><h2>让书章、他人研究和你的论文<br/>进入同一场争论。</h2><p>博士训练不是寻找一排同意你的引文。为当前问题主动配置不同角色的材料：谁支持、谁使问题复杂化、谁挑战、谁提供方法。</p><a href="https://gracieme.github.io/research-library/" target="_blank" rel="noreferrer">打开完整论文库 ↗</a></div><div className="paper-finder"><label>用研究问题或概念检索论文库<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如 identity negotiation / assessment equity"/></label>{libraryState==="loading"&&<p className="lab-status">正在连接论文库…</p>}{libraryState==="error"&&<p className="lab-status">暂时无法读取论文库。你仍可打开完整论文库，并在下方加入自己的论文。</p>}{libraryState==="ready"&&<div className="paper-results">{results.map(p=><article key={p.id}><div><b>{p.title}</b><small>{p.author}{p.year?` · ${p.year}`:""}</small></div><button disabled={selected.some(s=>s.paper.id===p.id)} onClick={()=>addSource(p)}>{selected.some(s=>s.paper.id===p.id)?"已加入":"加入争论 +"}</button></article>)}{query&&results.length===0&&<p className="lab-status">没有匹配结果，换一个概念或作者名试试。</p>}</div>}</div>
 <div className="constellation"><div className="constellation-head"><h3>本周证据组合</h3><span>{selected.length} 篇库内论文 + {ownPaper.trim()?"1 篇自己的论文":"自己的论文待加入"}</span></div><label className="own-paper"><b>你的论文 / Your own work</b><input value={ownPaper} onChange={e=>{setOwnPaper(e.target.value);localStorage.setItem("tl-own-paper",e.target.value)}} placeholder="输入论文题目或当前稿件名称"/><small>把自己的文章当作可被挑战的材料，而不是最终答案。</small></label>{selected.map(s=><article className={`source-row ${s.role}`} key={s.paper.id}><div><b>{s.paper.title}</b><small>{s.paper.author}</small></div><select aria-label={`设置 ${s.paper.title} 的论证角色`} value={s.role} onChange={e=>changeRole(s.paper.id,e.target.value as SourceRole)}><option value="supports">支持 Supports</option><option value="complicates">复杂化 Complicates</option><option value="challenges">挑战 Challenges</option><option value="method">方法借鉴 Method</option></select><button aria-label={`移除 ${s.paper.title}`} onClick={()=>removeSource(s.paper.id)}>×</button></article>)}<label className="synthesis-box"><b>Synthesis memo · 不要逐篇摘要</b><span>这些材料共同改变了你对问题的什么判断？分歧源于理论、方法、语境，还是证据尺度？你的论文处在争论的哪个位置？</span><textarea rows={7} value={synthesis} onChange={e=>{setSynthesis(e.target.value);localStorage.setItem("tl-synthesis",e.target.value)}} placeholder="Across these sources, the central disagreement is… My study enters this debate by…"/></label></div></section>
 <section className="idea-studio" id="ideas"><div><span>YOUR RESEARCH TRAJECTORY · 你的研究轨迹</span><h2>你不是缺少题目。<br/>你需要把已有论文长成研究计划。</h2><p>下面的启发来自论文库中反复出现的几条主线。它们不是替你宣布结论，而是把既有工作推进到更可检验、更能跨论文累积的位置。</p></div><div className="idea-grid">{inspirations.map((idea,i)=><article key={idea.title}><small>MOVE {String(i+1).padStart(2,"0")} · {idea.from}</small><h3>{idea.title}</h3><p>{idea.move}</p><b>下一步：为它找一篇支持证据和一个失败案例。</b></article>)}</div></section>
 <section className="record-shell" id="record"><div className="record-head"><div><span>WEEKLY INTELLECTUAL PRODUCT</span><h2>一章，一份可辩护的研究记录</h2></div><div className="completion"><b>{completeness}%</b><small>思考链完成度</small></div></div>
 <div className="record-context"><label>本周读哪本书？<select value={record.book} onChange={e=>update("book",e.target.value)}>{books.map(b=><option key={b}>{b}</option>)}</select></label><label>章节 / Chapter<input value={record.chapter} onChange={e=>update("chapter",e.target.value)} placeholder="例如 Chapter 6"/></label></div>
 <div className="record-fields">{fields.map(([key,title,zh,en])=><label key={key}><b>{title}</b><span>{zh}</span><small>{en}</small><textarea value={record[key]} onChange={e=>update(key,e.target.value)} rows={5} placeholder="先用自己的话写；允许保留不确定性。"/></label>)}</div>
 <div className="record-actions"><button onClick={save}>{saved?"已保存到这台设备 ✓":"保存进度"}</button><button className="secondary" onClick={exportMd}>导出 Markdown</button><small>记录只保存在当前浏览器；导出后可放进你的论文资料库。</small></div></section>
 <section className="defense-lab" id="defense"><div><span>ORAL QUALIFYING EXAM</span><h2>导师会继续追问什么？</h2><p>不要背答案。先限时 3 分钟作答，再针对追问补充证据和限定条件。</p></div><ol><li><b>Define.</b><p>Define your key concept without using the term itself. What adjacent concept must it not be confused with?</p></li><li><b>Warrant.</b><p>What evidence would distinguish your explanation from a plausible rival explanation?</p></li><li><b>Boundary.</b><p>Under what social, historical, or institutional conditions would your claim fail?</p></li><li><b>Power.</b><p>Whose interests become visible—or disappear—when you adopt this framework?</p></li><li><b>Revision.</b><p>What finding would make you change your mind, and how would your argument change?</p></li></ol></section>
 <footer><span>博士训练台</span><p>Reading → Position → Dissertation</p><a href="reading.html">返回四本书 →</a></footer></main>
}
