import {useMemo,useState} from"react";
const stages=[
 {phase:"FOUNDATION",title:"先建立你的起点立场",en:"Establish a baseline position",why:"博士训练从可修正的立场开始，而不是从背定义开始。现在的答案可以不成熟，但必须明确。",seminar:"Before reading more, tell me what you currently believe translanguaging is, what problem it solves, and where you suspect the concept may be overstated.",task:"用 150–250 字写出：你的定义、一个你认同的主张、一个你怀疑的主张。",prompt:"我目前把 translanguaging 理解为……它最有解释力的地方是……但我暂时不接受……",model:"一个合格的起点不会写‘跨语很重要’，而会区分描述性主张与规范性主张，例如：学习者确实调动整体 repertoire，并不自动证明所有课堂都应取消具名语言边界。",check:"你能否指出什么证据会让自己改变立场？"},
 {phase:"ARGUMENT",title:"学会重建，而不是复述",en:"Reconstruct an argument",why:"文献综述的基本单位不是摘要，而是 claim–warrant–evidence–limit。",seminar:"Read one chapter as an argument. Make the author’s case stronger and clearer than a casual reader could, before criticizing it.",task:"从四本书任选一章，分别写出核心主张、推理依据、使用的证据和结论边界。",prompt:"作者主张……因为……证据是……因此最多可以推出……",model:"‘本章讨论身份’不是论点；‘课堂跨语通过重新分配发言权改变可用身份位置’才是可检验主张。",check:"如果作者读到你的概括，会认为你公平吗？"},
 {phase:"CONCEPT",title:"追踪概念的谱系与边界",en:"Trace genealogy and boundaries",why:"博士生不能把相邻概念当同义词，也不能只使用自己喜欢的定义。",seminar:"A concept becomes useful when you can say what it excludes, how it changed, and which scholarly dispute its definition is trying to settle.",task:"选择一个概念，与两个相邻概念比较：来源、分析单位、解释对象、不能解释什么。",prompt:"X 与 Y 都关注……但 X 的分析单位是……Y 则……如果数据出现……我会选择 X。",model:"Translanguaging、code-switching 与 plurilingualism 可以观察同一事件，却基于不同本体论和研究目的；选择术语必须改变分析。",check:"不用这个概念，你会看不见什么？"},
 {phase:"EVIDENCE",title:"审查证据有没有撑住主张",en:"Audit the evidence",why:"很多有吸引力的理论主张，证据只能支持更小的结论。",seminar:"Separate what the data show, what the author infers, and what the author recommends. These are three different inferential moves.",task:"从论文库选一篇实证研究，写出：资料直接显示什么、作者推断什么、替代解释是什么。",prompt:"资料直接显示……作者进一步解释为……但同样可能是……要区分二者还需要……",model:"看到学生使用 L1 后完成任务，只能证明二者共现；要主张 L1 促成学习，还需要过程证据、比较或时间变化。",check:"你的结论有没有从相关性跳到机制或政策建议？"},
 {phase:"REBUTTAL",title:"提出最强反驳，再替作者回答",en:"Rebut and steelman",why:"批判不是缺点清单，而是找出一处足以改变结论的压力点。",seminar:"Attack the strongest version of the argument. Then switch chairs and give the strongest reply available to the author.",task:"写一段 objection、一段 author’s reply，再说明反驳后原主张还能保留多少。",prompt:"最强反驳是……作者可以回应……因此原主张应缩小／修改为……",model:"好的 rebuttal 不会说‘样本太小’便结束，而会说明样本结构为何使某个机制无法与替代解释区分。",check:"你的批评如果成立，会实际改变论文的哪一句结论？"},
 {phase:"SYNTHESIS",title:"让文献彼此争论",en:"Build a literature synthesis",why:"美国博士 seminar 看重你能否组织一场争论，而不是列出读过多少篇。",seminar:"Arrange sources by intellectual role—support, complication, challenge, and method—not by author or publication year.",task:"从论文库选四篇不同角色的研究，并加入你自己的一篇论文，写 300 字 synthesis memo。",prompt:"这些研究表面都讨论……真正分歧在于……差异可能来自……我的研究进入争论的位置是……",model:"综合不是 A 说、B 说、C 说；它要解释为何研究得到不同判断，并提出一个能容纳差异、同时可被证伪的新命题。",check:"删掉作者姓名后，读者还能看见清楚的争论结构吗？"},
 {phase:"DESIGN",title:"把立场变成可研究的问题",en:"Transfer position into design",why:"理论贡献只有在研究设计中产生可观察差异，才不是装饰性框架。",seminar:"Show how your ontology changes your unit of analysis, data collection, and the rival explanation you must rule out.",task:"从现有论文选择一个论点，写研究问题、分析单位、关键证据、反例和结论上限。",prompt:"如果我的解释成立，我应观察到……与竞争解释相比……一个会推翻它的案例是……",model:"若主张跨语扩大 epistemic participation，就要定义 participation 的序列指标，并观察谁的知识被接续、发展或忽略。",check:"另一位研究者能否用你的标准判断同一段资料？"},
 {phase:"VOICE",title:"形成自己的学术声音",en:"Claim a scholarly position",why:"你的目标不是站队，而是说清继承什么、修正什么、拒绝什么。",seminar:"Locate your work precisely: indebted to whom, departing where, and contributing what was not previously available.",task:"写一段 position statement，包含 intellectual debt、departure、contribution 和 boundary。",prompt:"我继承……关于……的判断；但在……上与其不同。本文提出……其适用范围限于……",model:"成熟声音可以同时说：unitary repertoire 纠正了双语能力的缺陷观，但分析仍须保留 named languages 作为制度化不平等的社会事实。",check:"这段话是否只有你能写，而不是任何研究都能套用？"},
 {phase:"DEFENSE",title:"在答辩中守住、缩小或修正",en:"Defend—and revise",why:"答辩不是永不认错；优秀博士知道何时守住核心、何时缩小主张。",seminar:"Answer in four moves: position, warrant, boundary, revision. Do not hide behind more literature when the question asks what you think.",task:"选择四位学者组成委员会，对同一论点完成限时回答，然后写答辩后的 revised claim。",prompt:"我的立场是……依据是……它不适用于……接受您的质疑后，我会把原主张修正为……",model:"最强回答准确承认一项限制，同时解释为什么它不会摧毁核心贡献，或如何据此修改贡献。",check:"你能在 90 秒内说出立场、证据、边界和修正吗？"},
] as const;
export default function GuidedProgramme(){
 const [completed,setCompleted]=useState<number[]>(()=>{try{return JSON.parse(localStorage.getItem("tl-programme-complete")||"[]")}catch{return []}});const firstOpen=useMemo(()=>stages.findIndex((_,i)=>!completed.includes(i)),[completed]);const [active,setActive]=useState(()=>Math.max(0,firstOpen));const [responses,setResponses]=useState<Record<number,string>>(()=>{try{return JSON.parse(localStorage.getItem("tl-programme-responses")||"{}")}catch{return {}}});const stage=stages[active];const done=completed.includes(active);const progress=Math.round(completed.length/stages.length*100);
 const updateResponse=(value:string)=>{const next={...responses,[active]:value};setResponses(next);localStorage.setItem("tl-programme-responses",JSON.stringify(next))};const complete=()=>{if(!responses[active]?.trim())return;const next=[...new Set([...completed,active])].sort();setCompleted(next);localStorage.setItem("tl-programme-complete",JSON.stringify(next));if(active<stages.length-1)setActive(active+1)};
 return <main className="programme"><header className="masthead"><a className="brand" href="reading.html"><span className="brand-mark">PhD</span><span>博士培养路径</span></a><nav><a href="workspace.html">资源与答辩室</a><a href="reading.html">四本书</a></nav></header><section className="programme-shell"><aside className="programme-rail"><div><span>YOUR PROGRAMME</span><b>{progress}%</b><small>{completed.length}/{stages.length} steps completed</small></div><ol>{stages.map((s,i)=><li key={s.phase}><button className={`${active===i?"active":""} ${completed.includes(i)?"done":""}`} onClick={()=>setActive(i)}><i>{completed.includes(i)?"✓":String(i+1).padStart(2,"0")}</i><span><small>{s.phase}</small>{s.title}</span></button></li>)}</ol><a href="workspace.html">打开论文库与学者委员会 →</a></aside><section className="programme-step"><div className="step-status"><span>STEP {String(active+1).padStart(2,"0")} / {String(stages.length).padStart(2,"0")} · {stage.phase}</span><b>{done?"已完成，可继续修订":"当前训练任务"}</b></div><h1>{stage.title}</h1><h2>{stage.en}</h2><div className="why-box"><b>为什么现在练这个？</b><p>{stage.why}</p></div><section className="supervisor-talk" lang="en"><span>SUPERVISOR’S SEMINAR</span><p>{stage.seminar}</p></section><section className="today-task"><span>DO THIS NOW</span><h3>这一步只完成一件事</h3><p>{stage.task}</p><textarea rows={10} value={responses[active]||""} onChange={e=>updateResponse(e.target.value)} placeholder={stage.prompt}/><div><small>{responses[active]?.trim()?"已有作答，可以提交。":"先写出你的答案，才可以完成这一步。"}</small><button disabled={!responses[active]?.trim()} onClick={complete}>{active===stages.length-1?"完成培养路径":"完成并进入下一步 →"}</button></div></section><section className="step-answer"><span>MODEL & STANDARD · 答案放在最后</span><details><summary>完成自己的答案后再展开</summary><h3>导师式示范</h3><p>{stage.model}</p><h3>口试检查</h3><p>{stage.check}</p></details></section><div className="step-nav"><button disabled={active===0} onClick={()=>setActive(active-1)}>← 上一步</button><button disabled={active===stages.length-1} onClick={()=>setActive(active+1)}>查看下一步 →</button></div></section></section></main>
}
