export type HandbookQuestion = { question: string; answer: string };
export type HandbookChapter = {
  order: number;
  chapter: number;
  unit: string;
  title: string;
  chinese: string;
  purpose: string;
  critical: string;
  questions: HandbookQuestion[];
};

const q = (question: string, answer: string): HandbookQuestion => ({ question, answer });

export const handbookChapters: HandbookChapter[] = [
  { order:1, chapter:1, unit:"A · 总框架", title:"Navigating Translanguaging: Decoloniality, Fluid Simultaneity and Multimodalities", chinese:"全书导航：去殖民、流动同时性与多模态", purpose:"先建立全书坐标：translanguaging 同时是一种语言实践观、分析视角与转化性议程。阅读时标出三条主线如何彼此支撑，又在哪里不能相互替代。", critical:"警惕把三个宏大概念并列后便视为已经完成论证。追问：去殖民是可检验的制度改变，还是价值标签？“流动”又如何解释稳定的语言等级？", questions:[q("为什么本章不能只被读成 translanguaging 的词典定义？","因为它承担的是编者导论：规定全书的问题空间、政治方向和分析尺度。定义只是起点，更重要的是三条主线如何组织后续章节。"),q("fluid simultaneity 对传统双语模型提出什么挑战？","它质疑把语言资源预先切成两个轮流启动的封闭系统，强调多种资源可在同一意义建构事件中协同出现。"),q("反驳：强调流动会不会使语言权利失去对象？","会有此风险。语言权利和公共政策常依赖可命名的语言共同体；较稳妥的立场是区分个体实践的流动性与制度分类的政治现实，而非取消后一层。")] },
  { order:2, chapter:6, unit:"A · 总框架", title:"Translanguaging and the Linguistic Capacity of Bilinguals", chinese:"跨语与双语者的语言能力", purpose:"厘清作者如何描述双语者的语言能力，以及这种描述与“两个单语系统相加”的模型有何不同。", critical:"不要从观察到的混合表达直接推导心智结构。行为证据、能力模型与政治主张属于不同推论层级。", questions:[q("linguistic capacity 与具体一次语言表现有何区别？","能力是可生成和理解意义的潜在资源与组织方式；表现则受任务、受众、规范和情境限制，不能由一次表现直接穷尽能力。"),q("为什么这一章应在教育章节之前读？","若没有能力观，课堂 translanguaging 容易退化为临时翻译技巧；能力观决定教师如何理解学习者资源。"),q("反驳：整合资源库是否否认语言间的结构差异？","不必然。整合能力可以承认资源之间存在统计、历史和结构模式；争论焦点是这些模式是否等同于心智中完全分离的命名语言。")] },
  { order:3, chapter:9, unit:"A · 总框架", title:"Translanguaging and Bilingual Cognition", chinese:"跨语与双语认知", purpose:"把社会实践论与认知研究对接，辨认加工、控制、激活和任务表现等主张各需要什么证据。", critical:"避免用神经或认知术语给社会理论制造虚假的科学确定性；也避免因政治立场而忽略可重复的心理语言学发现。", questions:[q("认知研究能回答 translanguaging 的哪些问题？","它可研究资源激活、加工代价、控制和任务条件，但不能单独裁决语言分类是否正义或教育政策应如何设计。"),q("为什么任务设计会改变双语认知研究的结论？","不同刺激、反应方式与语言提示会主动制造或强化边界，因此测到的可能是实验结构下的行为，而非固定的自然系统。"),q("反驳：若存在语言选择成本，是否足以证明两个完全分离系统？","不足。选择成本也可能来自熟练度、任务切换、社会提示或抑制机制；它支持某种区分效应，却不自动证明完整的双系统本体论。")] },
  { order:4, chapter:2, unit:"B · 语言观", title:"Integrating Languaging, Translanguaging, and Trans-semiotizing as Living Process", chinese:"作为生命过程的语言活动、跨语与跨符号", purpose:"理解 organicist-processual 视角为何把意义建构看成活的过程，而不是从库存中提取静态符号。", critical:"“生命”“有机”容易成为无法证伪的隐喻。要求作者说明它比互动论或多模态分析多预测、解释了什么。", questions:[q("process view 改变了什么分析单位？","焦点从稳定代码和成品句子，转向跨时间展开的身体、环境、知觉与符号协同。"),q("trans-semiotizing 为什么不只是换一种符号？","它关注符号资源在活动中互相转化、重组并产生新意义，而非把既定信息从一个容器搬到另一个容器。"),q("反驳：有机体隐喻的最大方法风险是什么？","它可能包容一切变化却不给出排除条件。研究必须提出可观察过程、时间尺度和与竞争解释不同的预测。")] },
  { order:5, chapter:3, unit:"B · 语言观", title:"Waterscape Epistemologies, Waves of Knowing and Translanguaging as Wet Ontology", chinese:"水景知识论、认知之浪与湿本体论", purpose:"用“水／波”重想边界、关系和知识生成，并区分启发性隐喻与经验命题。", critical:"流体隐喻可能美化流动并遮蔽堤坝、所有权和被迫迁移。阅读时同时寻找流动与阻断。", questions:[q("wet ontology 试图替换什么想象？","它替换把语言、文化和知识视为边界清楚、稳定容器的固体想象，强调渗透、关系和持续生成。"),q("如何把水的隐喻变成可分析的问题？","追踪资源如何流通、在哪里受阻、谁建造边界、流动改变了哪些关系，而不是只重复“语言是流动的”。"),q("反驳：流动隐喻为何可能不够政治？","因为流动并不说明谁能移动、谁被淹没以及谁控制通道；必须把权力、基础设施和历史重新放回分析。")] },
  { order:6, chapter:4, unit:"B · 语言观", title:"Languaging as Ritual", chinese:"语言活动作为仪式", purpose:"理解重复、程式、共同注意与社会秩序如何构成 languaging，并用它修正纯粹自发创造的叙事。", critical:"仪式视角可能高估秩序、低估即兴与断裂；检验作者如何解释偏离和失败。", questions:[q("为什么 ritual 能解释语言的稳定性？","意义在可重复的参与结构、期待和身体行动中被维持；稳定性由实践再生产，而非只来自抽象代码。"),q("仪式与创造是否矛盾？","不必然。创新往往依赖可识别的惯例作为背景，偏离惯例才能被参与者感知为有意义。"),q("反驳：把互动称为仪式会不会概念过宽？","会。若任何重复互动都算仪式，概念失去区分力；应明确参与角色、规范强度、象征效力和重复机制。")] },
  { order:7, chapter:5, unit:"B · 语言观", title:"The Politics of ‘Meaning’ in Translingual Practice", chinese:"跨语实践中“意义”的政治", purpose:"不把意义当作中性传递物，追踪谁能提出解释、谁的解释被承认，以及意义协商的物质后果。", critical:"不能把一切误解都归因于权力，也不能浪漫化协商。某些沟通确实需要稳定约定和精确对应。", questions:[q("意义为什么具有政治性？","因为可接受解释、合法说者与正确形式由制度和社会关系分配，意义确认会带来评价与资源后果。"),q("协商意义为何不是天然平等？","参与者拥有不同的中断权、修正权、专业权威和被相信程度，因此同样的表达并非获得同样解释机会。"),q("反驳：强调协商是否会削弱准确性？","若否认共享约定会有此风险。批判立场应检验准确标准如何形成和由谁承担代价，而不是取消医学、法律等场景对精确性的需要。")] },
  { order:8, chapter:7, unit:"C · 权力", title:"A Raciolinguistic Perspective on Translanguaging", chinese:"跨语的种族语言学视角", purpose:"把注意力从“有缺陷的说者”转到种族化的听者、评价制度和语言标准。", critical:"种族语言学解释很强，但不可使阶级、地域、性别、熟练度或真实可懂度问题自动消失。", questions:[q("raciolinguistic lens 改变了问题的主语吗？","改变了：不只问说者如何说，也问听者与制度如何把某些说法听成不足。"),q("为什么符合标准仍可能被判定为不够好？","评价并非只处理形式，种族化身份会影响口音、能力和专业性的感知。"),q("反驳：如何避免把所有负面评价都解释成种族化？","需要比较性证据、评价者模式、制度历史和替代变量；理论提供假设，而非免证据的结论。")] },
  { order:9, chapter:8, unit:"C · 权力", title:"Translanguaging Triad: Resistance, Decoloniality, and Transformative Praxis in the Global South", chinese:"抵抗、去殖民与转化实践三联", purpose:"区分抵抗性使用、去殖民知识批判与改变制度的 praxis，观察 Global South 如何改变理论生产中心。", critical:"不是所有非标准使用都是抵抗，也不是加入本土语言就完成去殖民。要求说明行动者意图、制度效果和长期变化。", questions:[q("三联结构为什么不能压缩成“允许母语”？","因为它同时涉及反抗规范、重估知识来源和集体改变实践条件，语言许可只是最低层动作。"),q("transformative praxis 比课堂策略多了什么？","它包含反思与行动循环，并以参与关系、知识权威或制度规则发生变化为判断依据。"),q("反驳：Global South 会不会被本质化？","会。南方内部同样存在国家、阶级和语言等级；它应是权力位置与知识生产关系的分析概念，而非同质地理身份。")] },
  { order:10, chapter:24, unit:"C · 权力", title:"Translanguaging, Individualization, and Unequal Englishes", chinese:"跨语、个体化与不平等英语", purpose:"识别制度如何把语言等级造成的问题转译成个人技能、努力或自信不足。", critical:"结构批判不能否认个体学习需求；关键是避免让个体单独承担由制度评价制造的全部成本。", questions:[q("什么是语言问题的 individualization？","把政策、劳动力市场或种族化标准造成的差距解释为个人能力和自我改善问题。"),q("为何 unequal Englishes 对流动性论述构成挑战？","即使实践流动，不同英语仍被制度赋予不等价值，资源的混合不会自动消除等级。"),q("反驳：强调结构会不会削弱学习者能动性？","可能。更好的框架同时支持个体获得有用资源，并要求机构改变不公平标准，拒绝二选一。")] },
  { order:11, chapter:10, unit:"D · 模态关系", title:"Translanguaging, Transmodalities, and Transpositioning", chinese:"跨语、跨模态与跨位置", purpose:"追踪语言、图像、身体、空间和社会位置如何共同生产意义。", critical:"概念增加不等于解释增加。每引入一个 trans- 术语，都要说明其独立分析价值和边界。", questions:[q("transmodality 与简单列举模态有何不同？","它关心模态之间如何转换、约束和重新赋值，而非只说明现场同时有声音、文字和图像。"),q("positioning 为什么属于意义分析？","人们在互动中被放置或自我放置为专家、学生、外来者等，这些关系位置改变表达如何被理解。"),q("反驳：多个 trans- 概念是否造成理论膨胀？","若缺少清晰区分会造成。应检验每个概念是否改变数据选择、分析步骤或可预期结论。")] },
  { order:12, chapter:25, unit:"D · 模态关系", title:"Transpositioning", chinese:"跨位置化", purpose:"集中理解参与者如何跨越和重构语言、身份、认识与互动位置。", critical:"如果任何身份变化都叫 transpositioning，它会与 positioning、stance 或 identity work 重叠。", questions:[q("transpositioning 的分析重点是什么？","不是给人贴固定身份，而是追踪位置如何在资源调动和关系变化中被重新组织。"),q("研究者应寻找什么证据？","指称、代词、语体、身体朝向、话轮权、知识声明及他人回应等位置变化的互动证据。"),q("反驳：它与普通 positioning theory 有何必要差异？","必要差异应体现在跨资源、跨尺度或跨边界的重新定位；若分析步骤和解释结果无差异，新术语便可能多余。")] },
  { order:13, chapter:23, unit:"D · 模态关系", title:"Translanguaging: Uncovering Networks for Unspeakable Significance", chinese:"网络与不可言说的意义", purpose:"从单个说者扩展到人、物、记忆、地点与沉默组成的意义网络。", critical:"“不可言说”不能成为拒绝分析或证据的保护罩；研究者仍需说明如何负责任地推断意义。", questions:[q("network view 为什么挑战个体资源库模型？","意义可能分布在人际关系、物件、历史和场所中，不能全部归入某个个体内部。"),q("沉默可以如何成为资料？","它可与停顿位置、身体动作、历史禁忌和参与者解释共同分析，但不能脱离语境任意赋义。"),q("反驳：研究者如何避免替参与者说出“不可言说”的意义？","采用参与者核对、多种资料、反身性记录和保持不确定性的表述，把解释权限制在证据所及范围。")] },
  { order:14, chapter:11, unit:"E · 研究", title:"Methodological Challenges and Opportunities in Translanguaging", chinese:"跨语研究的方法挑战与机会", purpose:"把理论承诺变成数据选择、转写、单位划分和分析程序。", critical:"方法若预设语言边界，却声称发现边界流动，会发生理论—方法不一致；反之，完全拒绝分类也会使分析不可复核。", questions:[q("为什么转写不是中性记录？","选择怎样标注语言、停顿、手势和重叠，会预先塑造读者看见的边界与行动。"),q("如何让分析可复核？","公开资料选择、转写规则、分析单位、反例处理和推论链，同时保留必要的多模态语境。"),q("反驳：拒绝命名语言后还如何描述资料？","可将参与者分类、制度标签和分析者识别分层标注，并说明每种标签的用途，而不是假装完全无分类。")] },
  { order:15, chapter:12, unit:"E · 研究", title:"Ethics and Translanguaging Research", chinese:"跨语研究伦理：身份与参与者关系", purpose:"把伦理从一次审批扩展到翻译、署名、解释权、关系维护和研究成果流通。", critical:"“与参与者关系良好”不等于权力平等；参与式语言也可能掩盖研究者最终控制发表。", questions:[q("研究者身份为何影响资料？","研究者的语言、机构、种族与专业位置会改变参与者说什么、如何被翻译以及哪些解释获得权威。"),q("macroethics 与 microethics 如何互补？","前者处理审批、存储和制度规则，后者处理现场即时关系判断；合规不能替代情境伦理。"),q("反驳：成员核对是否能消除解释权问题？","不能。参与者内部可能意见不同，且核对受时间、资源和研究语言限制；它是约束解释的一种机制，不是绝对认证。")] },
  { order:16, chapter:13, unit:"F · 教育", title:"Bilingual Education and Translanguaging", chinese:"双语教育与跨语", purpose:"区分把 translanguaging 当支架、教学设计原则和制度转化方案的不同层级。", critical:"若最终目标和高风险评价仍是单语规范，课堂中的自由使用可能只是通往同化的临时工具。", questions:[q("strategic translanguaging 与自发实践有何区别？","前者由教师围绕学习目标设计资源与活动；后者是学习者日常自然调动资源，两者可互动但不可混称。"),q("如何判断课堂设计是否转化性？","看它是否改变知识参与、语言价值与评价权，而非只看课堂出现了几种语言。"),q("反驳：学生是否仍需要发展特定命名语言？","通常需要。资源整合与特定语域训练可以并存；问题是不能把后者变成贬低全部资源库的理由。")] },
  { order:17, chapter:14, unit:"F · 教育", title:"Translanguaging, Biliteracy, Multiliteracies, and Critical Literacy", chinese:"跨语、双语读写、多元读写与批判读写", purpose:"连接语言资源、文本形式、媒介和权力阅读，比较四个框架各自承担的工作。", critical:"多种资源的出现不自动等于 critical literacy；必须看学习者是否分析并改变文本背后的权力关系。", questions:[q("biliteracy 与 multiliteracies 的焦点有何差异？","前者常关注跨语言读写发展，后者更广泛处理多模态、文化与媒介差异；具体章节定义仍需精读确认。"),q("怎样使跨语读写具有批判性？","让学生追问谁被代表、谁被沉默、何种语言形式获得权威，并为真实受众重构文本。"),q("反驳：多模态作品会不会回避严密写作？","可能。设计应明确不同目标：允许多模态意义建构，同时对需要发展的特定文本体裁提供显性教学和独立评价。")] },
  { order:18, chapter:15, unit:"F · 教育", title:"Translanguaging, EMI, and Language-of-Instruction Policies", chinese:"跨语、EMI 与教学语言政策", purpose:"观察英语授课政策、课堂实际资源与学生可及性之间的张力。", critical:"课堂中的教师变通可能缓解问题，却也可能替不公平 EMI 政策兜底，使制度无需改变。", questions:[q("policy 与 practice 为什么常不一致？","政策用单一教学语言表述合法性，真实课堂却需调动多种资源完成解释、参与和关系管理。"),q("如何评价 EMI 中的 translanguaging？","同时检查内容学习、特定英语发展、参与公平、教师工作量和政策后果。"),q("反驳：允许跨语是否必然改善 EMI？","不必然。若教师不共享学生资源、教材和考试仍单语，或使用方式污名化，效果可能有限甚至加剧分层。")] },
  { order:19, chapter:16, unit:"F · 教育", title:"Translanguaging in Foreign Language Education", chinese:"外语教育中的跨语", purpose:"处理目标语练习与完整资源库之间的张力，区分最大化接触与强制排除。", critical:"批判“目标语唯一”不代表暴露量和自动化练习无关紧要；应比较不同任务阶段的真实学习效果。", questions:[q("为何外语课堂特别容易抵抗 translanguaging？","课程常以目标语沉浸、纯正性和可计量接触时间为核心合法性。"),q("何时使用已有语言资源最有价值？","复杂概念比较、元语言反思、身份表达和策略规划中常有价值，但需由目标和证据决定。"),q("反驳：跨语会不会减少目标语练习？","可能，尤其在时间有限且设计松散时。解决方案是按任务功能配置资源，而非无条件禁止或无条件开放。")] },
  { order:20, chapter:22, unit:"F · 教育", title:"A Critical Translanguaging Lens on Assessment", chinese:"评估的批判性跨语视角", purpose:"区分知识、沟通能力和特定语言形式，检查考试如何制造而非只测量能力。", critical:"完全开放资源可能改变构念，使成绩无法回答原测试问题；公平改革必须先明确要测什么。", questions:[q("construct-irrelevant language demand 是什么问题？","当测试目标并非某种语言形式，语言门槛却阻碍学生展示目标知识时，它引入了与构念无关的负担。"),q("跨语评估如何保持解释力？","预先界定构念、允许与目标一致的资源、记录支持条件，并分别报告内容与特定语言表现。"),q("反驳：统一单语测试是否一定不公平？","不一定；若构念就是特定语言语域，它可能合理。批判点在于标准是否与目的对齐、后果是否被审查，而非形式统一本身。")] },
  { order:21, chapter:17, unit:"G · 社区复兴", title:"Community-Based Language Education and Translanguaging", chinese:"社区语言教育与跨语", purpose:"把知识中心从学校移向家庭、长者、社区组织和地方实践。", critical:"“社区”不是和谐单体；代际、性别、阶级和语言纯正观可能造成内部权力差异。", questions:[q("社区教育改变了谁是教师？","知识权威可分布于家人、长者、文化实践者和学习者，不再只属于持证教师。"),q("为什么场所是语言学习的一部分？","地方活动、物件、历史和关系为语言资源赋予用途与意义，不能完全复制进教室。"),q("反驳：community voice 是否能作为单一立场？","不能。研究与课程需呈现内部异议、代表机制和谁没有被邀请发言。")] },
  { order:22, chapter:18, unit:"G · 社区复兴", title:"Translanguaging and Historically Based Language Trauma", chinese:"以跨语回应历史性语言创伤", purpose:"理解殖民惩罚、羞耻和代际断裂如何进入当下语言实践，并讨论修复条件。", critical:"创伤框架能解释痛苦，也可能把群体固定为受害者；必须同时看延续、能动性和制度责任。", questions:[q("historically based trauma 为什么不是个人焦虑？","它由禁令、惩罚、土地与教育制度等历史过程产生，并通过家庭和机构跨代延续。"),q("跨语实践如何参与修复？","它可降低纯正门槛、重新连接代际资源并承认被压抑的表达方式，但不能替代制度赔偿和资源投入。"),q("反驳：允许混合会不会威胁弱势语言复兴？","在强势语言压力下确有风险。应由社区目标决定何时扩展资源、何时建立弱势语言保护空间，而非套用普遍答案。")] },
  { order:23, chapter:19, unit:"G · 社区复兴", title:"Translanguaging and Language Revitalization: Higher Education in Africa", chinese:"非洲高等教育中的跨语与语言复兴", purpose:"考察高校知识生产、专业术语和语言政策如何支持或限制复兴。", critical:"高校 translanguaging 可能提升可及性，却未必带来弱势语言的跨代家庭使用；复兴指标必须多层化。", questions:[q("高等教育为什么是语言复兴的重要场域？","它控制专业知识、资格认证与术语生产，决定弱势语言能否进入高地位功能。"),q("如何判断复兴不只是象征展示？","检查课程、出版、师资、预算、评价和持续使用是否发生结构变化。"),q("反驳：跨语会不会让强势英语继续占据核心？","会。若本土语言只用于解释而英语负责正式文本与认证，等级可能被重演；需追踪功能分配和资源流向。")] },
  { order:24, chapter:20, unit:"H · 可及性", title:"Deaf Education: Translanguaging Through Tied Hands", chinese:"聋人教育：被束缚双手的跨语", purpose:"通过手语、口语、文字和身体重新审视语言边界，并关注制度如何限制可用资源。", critical:"不能把聋人经验当作扩展听人理论的例证；应优先处理聋人知识、手语权利和具体可及性。", questions:[q("本章如何挑战以声音为中心的语言观？","它显示意义可通过手、脸、空间、文字和技术组织，声音不是语言能力的默认中心。"),q("“tied hands”提示什么制度问题？","可指向禁止或限制手语、缺乏合格师资与解释服务等使资源不能自由调动的条件。"),q("反驳：多模态开放是否足以保障聋人教育？","不足。若没有充分可及的自然语言输入、手语环境与制度权利，多模态口号可能掩盖语言剥夺。")] },
  { order:25, chapter:21, unit:"H · 可及性", title:"From ‘Disordered’ Language to Expansive Languaging", chinese:"从“语言障碍”到扩展性语言活动", purpose:"检查特殊教育如何通过单语、标准化和常模把差异病理化，同时保留对真实支持需求的识别。", critical:"反缺陷话语不能否认障碍、痛苦和专业支持价值；关键是区分身体／认知差异与制度制造的限制。", questions:[q("为什么 diagnosis 可能受语言意识形态影响？","评估工具和常模常以单语、特定文化互动为标准，使差异被误判为缺陷。"),q("expansive languaging 改变怎样的教育反应？","它先扩大可用资源和参与方式，再判断学习者需要何种支持，而非先要求符合单一表达规范。"),q("反驳：去病理化是否意味着取消诊断？","不意味着。诊断可带来服务；应改进多语评估、功能证据和共同决策，避免以批判话语撤走支持。")] },
  { order:26, chapter:26, unit:"I · 媒介跨界", title:"Translanguaging and Visuality", chinese:"跨语与视觉性", purpose:"研究图像、版式、可见性和观看权力如何与语言资源共同构成意义。", critical:"视觉材料不是天然跨语言或民主；可见性也可能带来监控、刻板化和平台剥削。", questions:[q("visuality 为什么不等于“图片的意思”？","它还研究谁被看见、谁观看、观看制度和视觉资源如何组织社会关系。"),q("怎样分析语言与视觉的互相约束？","比较文字、构图、颜色、镜头和平台界面各自承担的意义，以及删除其中一项会改变什么。"),q("反驳：加入视觉分析后 translanguaging 是否变成一般多模态？","若不说明跨资源重组与语言政治的独特贡献，确有此风险；分析应明确概念增量。")] },
  { order:27, chapter:27, unit:"I · 媒介跨界", title:"Translanguaging, Creativity, and the Arts", chinese:"跨语、创造力与艺术", purpose:"考察艺术如何重组符号边界、受众位置和可表达经验。", critical:"新奇不等于政治抵抗；艺术跨语也可能被市场消费为异国风格。", questions:[q("艺术场域为何适合观察 translanguaging？","艺术容许语言、声音、身体、材料和空间以非命题方式协作，边界重组尤其可见。"),q("如何区分创造性与批判性？","创造性产生新组合；批判性进一步暴露或改变规则与权力，两者可能重合但不自动等同。"),q("反驳：混合风格是否天然颠覆规范？","不是。需检查生产条件、受众解读、收益归属和制度后果；混合也可能强化刻板印象。")] },
  { order:28, chapter:28, unit:"I · 媒介跨界", title:"Translanguaging and the Digital World", chinese:"跨语与数字世界", purpose:"把平台、算法、界面、自动翻译和网络社群视为意义建构的参与条件。", critical:"“线上自由”容易忽略审核、数据抽取、数字鸿沟和算法对语言可见性的控制。", questions:[q("平台 affordance 如何塑造跨语？","字符限制、字幕、推荐、输入法和模板鼓励某些组合并阻碍另一些表达。"),q("数字跨语的数据单位可以是什么？","除帖子文字外，还包括线程、视频、声音、界面、转发轨迹、算法暴露和跨平台迁移。"),q("反驳：用户创新能否抵消平台权力？","通常不能完全抵消。能动性真实存在，但可见性、获利和封禁仍由基础设施不对称地分配。")] },
  { order:29, chapter:29, unit:"I · 媒介跨界", title:"Translation and Translanguaging", chinese:"翻译与跨语", purpose:"正面对照 translation 与 translanguaging，避免把一个吸收进另一个而失去专业边界。", critical:"若所有翻译过程都被重新命名为 translanguaging，会抹去目标文本、委托、等值、责任和职业规范等翻译学问题。", questions:[q("translation 与 translanguaging 的分析焦点可如何区分？","翻译常关注被社会识别为跨语言对应的产品与专业行动；跨语更广泛关注整合资源的意义过程。"),q("二者在哪里重叠？","译者准备、协商、笔记、工具使用和受众调整都可能呈现跨资源过程。"),q("反驳：translanguaging 能否取代 translation？","不能充分取代。它能丰富过程分析，但翻译的制度角色、产品责任和伦理需要独立概念保留。")] },
  { order:30, chapter:31, unit:"I · 媒介跨界", title:"Translanguaging and Interculturality", chinese:"跨语与跨文化性", purpose:"从固定文化差异转向互动中形成的文化分类、身份和关系。", critical:"反本质主义若走得过远，会使历史、群体知识和制度化文化差异难以命名。", questions:[q("interculturality 与文化知识清单有何不同？","它研究文化相关性如何在具体互动中被调用、协商和质疑，而非预设每个人代表固定文化。"),q("跨语如何参与文化定位？","语言、语体、称谓、故事和模态资源可让参与者接受、拒绝或重构文化归属。"),q("反驳：文化是否只是互动产物？","不是全部。互动受历史、法律、教育和集体记忆制约；应同时分析情境生成与结构延续。")] },
  { order:31, chapter:30, unit:"J · 边界审判", title:"Translanguaging, Gender, and Sexuality", chinese:"跨语、性别与性", purpose:"研究语言资源、声音、身体与命名如何共同实践性别和性，而非把身份视为固定变量。", critical:"“trans”之间的词形相似不能代替理论桥梁；需避免把跨性别经验比喻化为语言流动。", questions:[q("为什么 gender／sexuality 不能只作为人口变量？","它们在称谓、代词、语体、身体表现和制度回应中持续被生产和协商。"),q("交叉性在本章分析中意味着什么？","性别与性不能脱离种族、阶级、语言地位和迁移身份单独解释。"),q("反驳：translanguaging 与 transgender 的连接有何伦理风险？","可能挪用跨性别经验为理论隐喻。有效连接必须尊重具体群体知识，并展示可验证的共同机制而非文字游戏。")] },
  { order:32, chapter:32, unit:"J · 边界审判", title:"From Translanguaging to Transraciality", chinese:"从跨语到跨种族性", purpose:"检验语言边界分析如何延伸到种族分类、批判性种族语言意识和 radical listening。", critical:"种族与语言边界历史不同、物质后果不同；类比若过快，可能把反种族主义变成抽象的“边界流动”。", questions:[q("radical listening 为什么把责任转向听者？","它要求听者审查自己的分类、期待和权力，而非只训练被种族化说者调整表达。"),q("critical raciolinguistic awareness 需要看见什么？","语言标准如何与种族分类共同自然化，以及这种关系如何进入教学、评价和自我认知。"),q("反驳：transraciality 会不会淡化种族结构？","若被理解为个人自由跨越身份，风险很高；可辩护用法必须聚焦拆解种族化边界的制度实践，而非宣称结构已流动消失。")] },
  { order:33, chapter:33, unit:"J · 边界审判", title:"Hard Translanguaging: A Mutualizing Practice of Abun-Dance", chinese:"Hard Translanguaging：丰盛共舞的互化实践", purpose:"把本章当作全书压力测试：它如何推进、拒绝或重写前面形成的 translanguaging 核心？", critical:"激进新词可能带来伦理与想象力，也可能降低可理解性、可检验性与跨研究累积。要求概念承担解释责任。", questions:[q("为什么把本章安排在最后？","只有掌握全书的能力、权力、方法和教育争论后，才能判断激进扩展是必要推进还是概念过载。"),q("评价新概念需要哪些标准？","定义边界、与既有概念差异、可观察证据、解释增量、伦理后果和可反驳条件。"),q("最终反驳：translanguaging 是否已经扩展得过宽？","这是开放判断。若它仍能稳定说明资源边界如何被制度化并在实践中重组，就有核心；若任何关系性创造都算，则可能失去区分力。") ] },
];

export const handbookUnits = [...new Set(handbookChapters.map((chapter) => chapter.unit))];
