import{useState}from"react";
const risks=[
 ["01","研究装得太多","Translanguaging、IC、NoM/LRE、affect、identity、teacher agency、multimodality、assessment、raciolinguistics 与 decoloniality 同时承担核心解释任务。","保留 learner electivity、微观互动和制度条件；其余概念必须被分配为现象、描述工具、条件或批判解释。"],
 ["02","研究问题跨越过多尺度","现有四题从学生理由跳到能力发展、教师决策，再跳到文化意识形态与去殖民深度。","改成三步：互动中如何开放或限制资源 → 学习者如何采用或拒绝 → 这些模式如何被课程、评估与制度条件塑造。"],
 ["03","方法是相加，不是整合","CA-informed DA、ethnography、multimodal analysis、thematic analysis 与 CDA 目前都在场，却没有明确分工。","先做 ethnographic mapping，再选 focal episodes 做 multimodal sequential analysis，最后才连接访谈、文件与批判解释。"],
 ["04","Decolonial claim 风险很高","项目援引 Te Tiriti、te reo Māori 与 Indigenous epistemology，但研究场域是大学中文课程，未呈现 Māori governance。","当前采用 bounded route：研究制度去殖民承诺的可能与限度，不宣称项目本身完成 decolonisation。"],
 ["05","语料规模超过微观分析能力","3–4 班、30 小时录像、18 名学生、多轮访谈、ELAN、NVivo 和文件分析无法同等深入。","保留 3–4 班作生态描绘，只选两个 focal ecologies 与约 20–30 个关键互动事件深描。"],
 ["06","预期结果超过证据能力","Psychological safety、motivation、target-language development 等都被列为可能结果，但没有相应测量。","主结果限于 participation、stance 与 locally achieved meaning；身份和情感需要序列证据与参与者叙述相互支持。"],
];
const lenses=[
 ["Leo van Lier","Ecological agency","选择不是个人内部特质，而产生于学习者与课堂 affordances 的关系。观察学习者如何察觉、采用或改造可用机会。"],
 ["Darvin & Norton","Investment","有动机不等于愿意投入某种课堂实践。Identity、capital 与 ideology 决定一个选项是否值得、是否安全。"],
 ["Danping Wang","CSL language choice","中文课堂中的语言选择由个人、教学、专业、制度和社会多层条件共同形成，也是师生共同建构的。"],
 ["Conversation Analysis","Displayed orientation","不能从一次沉默或语言切换直接推断 preference 或 resistance；必须寻找参与者在序列中显示的取向。"],
 ["García / Li Wei","Repertoire legitimacy","区分整体 repertoire 的意义建构能力与具名语言作为学校和政治制度事实的后果。"],
 ["Flores & Rosa / Kubota","Power audit","追问谁的选择被承认为能力，谁承担选择的风险，以及‘自由选择’是否遮蔽不平等条件。"],
];
export default function ProposalClinic(){const [draft,setDraft]=useState(()=>localStorage.getItem("tl-electivity-draft")||"");return <main className="clinic"><header className="masthead"><a className="brand" href="programme.html"><span className="brand-mark">PhD</span><span>Proposal Clinic</span></a><nav><a href="programme.html">培养路径</a><a href="workspace.html">资源室</a><a href="#task">当前任务</a></nav></header>
<section className="clinic-verdict"><span>SUPERVISOR’S VERDICT · 20-PAGE PROPOSAL REVIEW</span><h1>这是一项有博士潜力的研究。<br/>现在需要的不是加法，而是减法。</h1><div><p>最有原创潜力的不是再次证明 translanguaging 有益，而是解释：大学中文课堂中的 learner electivity 如何在互动中形成，以及教师与制度条件如何决定哪些语言选择是可用的、正当的和有后果的。</p><aside><b>Decision</b><strong>Major conceptual revision</strong><small>保留场域与核心问题，重建理论和方法架构。</small></aside></div></section>
<section className="thesis-spine"><span>RECOMMENDED THESIS SPINE</span><h2>This study investigates how learner electivity over multilingual and multimodal resources is interactionally negotiated in university CSL classrooms, and how teacher practices and institutional conditions shape when such choices become available, legitimate, and consequential for participation.</h2><p>导师意见：先让这句话统领 proposal。Interactional competence 暂时作为对话对象，不要同时承诺重新定义它的语言、情感、身体、能动性和意识形态全部维度。</p></section>
<section className="clinic-rqs"><div><span>RESEARCH QUESTIONS</span><h2>把四个大问题<br/>收束为三步推论。</h2></div><ol><li><b>Interactional availability</b><p>How do learners and teachers interactionally make multilingual and multimodal resources available, optional, expected, or sanctionable in university CSL classrooms?</p></li><li><b>Learner uptake and consequence</b><p>How do learners take up, limit, or decline these resources, and what locally demonstrable consequences do these choices have for participation, meaning negotiation, and stance?</p></li><li><b>Institutional conditioning</b><p>How are these interactional patterns interpreted by participants and conditioned by course goals, assessment practices, and institutional language commitments?</p></li></ol></section>
<section className="risk-board"><div><span>WHAT THE COMMITTEE WILL ATTACK</span><h2>六个必须先处理的风险</h2></div><div>{risks.map(r=><article key={r[0]}><span>{r[0]}</span><h3>{r[1]}</h3><p>{r[2]}</p><b>导师要求</b><p>{r[3]}</p></article>)}</div></section>
<section className="electivity-lab" id="task"><div className="lab-title"><span>CURRENT SUPERVISION TASK</span><h2>Learner electivity</h2><p>你未必已经有答案。按三层提示逐步进入，不要直接抄示范答案。</p></div><div className="hint-levels"><details><summary><b>提示 1</b>先区分它不是什么</summary><p>它不是 preference：喜欢不等于能够行动。它不是抽象 agency：它专门研究多个语言／符号行动方案如何在具体时刻成为可选。它也不是自由选择：所有选择都有成本与制度边界。</p></details><details><summary><b>提示 2</b>向这些学者借支架</summary><div className="lens-grid">{lenses.map(l=><article key={l[0]}><h3>{l[0]}</h3><small>{l[1]}</small><p>{l[2]}</p></article>)}</div></details><details><summary><b>提示 3</b>判断 meaningful electivity</summary><ol><li>存在实际可用的 alternatives</li><li>学习者的理由可以被理解</li><li>拒绝首选规范不会带来不成比例的代价</li><li>选择得到互动中的 recognition，并改变后续行动</li></ol><p>因此，“教师说可以自由选择语言”不是充分证据。</p></details></div><section className="clinic-writing"><h3>现在写 150–250 词</h3><p>Define learner electivity, identify observable indicators, distinguish meaningful choice from constrained compliance, and name one rival interpretation.</p><textarea rows={11} value={draft} onChange={e=>{setDraft(e.target.value);localStorage.setItem("tl-electivity-draft",e.target.value)}} placeholder="Learner electivity refers to… It can be observed when… However, an apparent choice may instead reflect…"/><small>{draft.trim()?draft.trim().split(/\s+/).length:0} words · 自动保存在当前浏览器</small></section><section className="clinic-model"><span>MODEL ANSWER · 最后再看</span><details><summary>完成自己的版本后展开</summary><p lang="en">Learner electivity refers to learners’ interactionally accomplished and institutionally conditioned capacity to take up, limit, decline, or renegotiate available linguistic and semiotic resources. It differs from preference because a stated preference may not constitute an actionable choice, and from agency because it focuses on how alternative courses of action become available and consequential in particular classroom moments. Drawing on ecological accounts of agency, electivity emerges through learners’ engagement with classroom affordances rather than residing solely within individuals. Investment theory further suggests that learners’ choices are shaped by identity, capital, and ideology. Electivity can be observed when learners demonstrably orient to alternatives—for example, by accepting or rejecting translation, requesting permission to change languages, persisting with Mandarin after assistance is offered, or renegotiating a teacher’s expectation. Such actions should not automatically be interpreted as free choice. A choice becomes meaningfully elective only when alternatives are practically available, refusal does not carry disproportionate costs, and the decision receives interactional recognition. A rival interpretation is that apparent electivity reflects proficiency, task difficulty, or assessment pressure; the analysis must actively test these explanations.</p><b>继续反驳：这份答案仍需要解释 electivity 是 IC 的组成部分，还是 IC 得以表现的条件。</b></details></section></section>
<section className="supervision-order"><span>DO NOT REWRITE EVERYTHING YET</span><h2>导师给你的修订顺序</h2><ol><li><b>现在</b><p>完成 learner electivity 定义。</p></li><li><b>然后</b><p>确定它与 interactional competence 的关系。</p></li><li><b>第三步</b><p>用核心现象重写三个研究问题。</p></li><li><b>第四步</b><p>建立 theory-to-data 分析架构。</p></li><li><b>最后</b><p>再改 literature review、method 和 contribution。</p></li></ol><a href="programme.html">回到博士培养路径 →</a></section></main>}
