import{useState}from"react";
const lenses=[["Leo van Lier","先看课堂提供了哪些真正可用的 affordances；选择产生于学习者和环境的关系。"],["Darvin & Norton","再问 identity、capital 与 ideology 如何让一个选项变得值得、安全或难以承受。"],["Danping Wang","把中文课堂语言选择放回个人、教学、专业和制度多层条件中，不把它当成个人偏好。"],["Conversation Analysis","不要从一次沉默或切换直接推断 resistance；寻找参与者在序列中显示的取向。"]];
const later=[["理论范围","目前概念很多。等核心定义稳定后，我们再决定 IC、NoM/LRE、affect、identity 与 decoloniality 各自承担什么功能。"],["研究问题","四个问题跨越多个尺度。下一轮收束为：资源如何成为可选 → 学习者如何取用或拒绝 → 制度如何塑造这些模式。"],["方法架构","之后再把 ethnography、multimodal sequential analysis、访谈和制度文件排成先后关系，不同时开工。"],["Aotearoa 定位","保留批判视角，但先采用 bounded claim：研究去殖民承诺的可能与限度，而不预先宣称实现 decolonisation。"],["可行性","保留宽一些的课堂观察，只对少量 focal episodes 做精细多模态分析。"]];
export default function ProposalClinic(){
 const [draft,setDraft]=useState(()=>localStorage.getItem("tl-electivity-draft")||"");const words=draft.trim()?draft.trim().split(/\s+/).length:0;
 return <main className="clinic coach-clinic"><header className="masthead"><a className="brand" href="programme.html"><span className="brand-mark">PhD</span><span>和导师改 Proposal</span></a><nav><a href="programme.html">培养路径</a><a href="workspace.html">需要更多材料</a></nav></header>
 <section className="coach-today"><div><span>OUR SUPERVISION MEETING · 本次只走一步</span><h1>今天，我们先把<br/><em>learner electivity</em> 说清楚。</h1><p>你的 proposal 有很好的研究直觉。现在不要整篇重写，也不用一次解决所有理论问题。我们先找到一个能够统领全文的核心现象。</p></div><aside><small>今天完成什么？</small><b>一段 150–250 词的暂定定义</b><p>它不必完美。下一次我们会一起检验并修正。</p><a href="#write">开始写 ↓</a></aside></section>
 <section className="coach-why"><div><span>WHY THIS FIRST?</span><h2>为什么我让你先做这个？</h2></div><p>因为你真正有新意的地方，不是再次说明 translanguaging 有帮助，而是注意到学习者可能采用、限制或拒绝多语资源。这个现象能把课堂互动、教师决定和制度压力连成一条线。</p></section>
 <section className="coach-path"><span>我会怎样陪你推进</span><ol><li className="current"><b>现在</b><p>定义 learner electivity</p></li><li><b>下一次</b><p>判断它与 interactional competence 的关系</p></li><li><b>再下一次</b><p>重写研究问题</p></li><li><b>之后</b><p>让理论与资料分析一一对应</p></li><li><b>最后</b><p>回头重写整份 proposal</p></li></ol></section>
 <section className="coach-work" id="write"><div className="coach-prompt"><span>STEP 1 · THINK WITH ME</span><h2>先不用回答。依次打开提示。</h2><details><summary>提示一：它不是什么？</summary><p>它不只是 preference：喜欢不等于能够行动。它也不是笼统的 agency：它专门关注多个语言／符号行动方案如何在某一时刻成为可选。它更不等于自由选择，因为选择总有成本和制度边界。</p></details><details><summary>提示二：向哪些学者借支架？</summary><div className="coach-lenses">{lenses.map(l=><article key={l[0]}><b>{l[0]}</b><p>{l[1]}</p></article>)}</div></details><details><summary>提示三：怎样判断 meaningful electivity？</summary><p>检查四件事：是否存在实际可用的 alternatives；学习者的理由能否被理解；拒绝主导规范是否会付出过高代价；选择是否获得互动中的 recognition 并改变后续行动。</p></details></div>
 <section className="coach-writing"><span>YOUR WORKING ANSWER</span><h2>现在写一个可以被修改的答案</h2><p>请包含：定义、可观察指标、受约束的表面选择，以及一个 rival interpretation。</p><textarea rows={12} value={draft} onChange={e=>{setDraft(e.target.value);localStorage.setItem("tl-electivity-draft",e.target.value)}} placeholder="Learner electivity refers to… It can be observed when… However, an apparent choice may instead reflect…"/><div><small>{words} words · 自动保存</small><b>{words>=150&&words<=250?"长度合适，我们下一步可以讨论内容。":words?"先把意思写完整，字数之后再调。":"从一句不完美的定义开始就好。"}</b></div></section></section>
 <section className="coach-model"><span>导师的参考版本 · 不是标准答案</span><details><summary>写完自己的版本后，再看我的示范</summary><p lang="en">Learner electivity refers to learners’ interactionally accomplished and institutionally conditioned capacity to take up, limit, decline, or renegotiate available linguistic and semiotic resources. It differs from preference because a stated preference may not constitute an actionable choice, and from agency because it focuses on how alternative courses of action become available and consequential in particular classroom moments. Electivity can be observed when learners demonstrably orient to alternatives—for example, by accepting or rejecting translation, requesting permission to change languages, persisting with Mandarin after assistance is offered, or renegotiating a teacher’s expectation. Such actions should not automatically be interpreted as free choice. A choice becomes meaningfully elective only when alternatives are practically available, refusal does not carry disproportionate costs, and the learner’s decision receives interactional recognition. A rival interpretation is that apparent electivity reflects proficiency, task difficulty, identity positioning, or assessment pressure; the analysis must actively test these explanations.</p><aside><b>我还没有替你解决的问题</b><p>Electivity 究竟是 interactional competence 的组成部分，还是能力得以表现的条件？我倾向于后者，但要等你的定义稳定以后再决定。</p></aside></details></section>
 <section className="coach-later"><details><summary>其他问题怎么办？先替我收好，不必今天处理</summary><div>{later.map(item=><article key={item[0]}><b>{item[0]}</b><p>{item[1]}</p></article>)}</div></details></section>
 <footer><span>Proposal Supervision</span><p>一次只把一个问题想深。</p><a href="programme.html">返回培养路径 →</a></footer></main>
}
